from typing import (
    Callable,
    Any,
    Union,
    Dict,
    Tuple,
    Set,
    List,
)
from dearpygui import dearpygui
from dearpypixl.components.item import Item
from dearpypixl.components.configuration import ItemAttribute

##################################################
####### NOTE: This file is auto-generated. #######
##################################################

__all__ = [
    "Theme",
    "ThemeComponent",
    "ThemeColor",
    "ThemeStyle",
]


class Theme(Item):
    """Adds a theme.
    
    	Args:
    		label (str, optional): Overrides 'name' as label.
    		user_data (Any, optional): User data for callbacks
    		use_internal_label (bool, optional): Use generated internal label instead of user specified (appends ### uuid).
    		tag (Union[int, str], optional): Unique id used to programmatically refer to the item.If label is unused this will be the label.
    		id (Union[int, str], optional): (deprecated) 
    		default_theme (bool, optional): (deprecated) 
    	Returns:
    		Union[int, str]
    """

    label             : str      = ItemAttribute("configuration", "get_item_config", "set_item_config", None)
    user_data         : Any      = ItemAttribute("configuration", "get_item_config", "set_item_config", None)
    use_internal_label: bool     = ItemAttribute("configuration", "get_item_config", "set_item_config", None)

    _is_container     : bool     = True                                                                      
    _is_root_item     : bool     = True                                                                      
    _is_value_able    : bool     = False                                                                     
    _unique_parents   : tuple    = ()                                                                        
    _unique_children  : tuple    = ('ThemeComponent',)                                                       
    _unique_commands  : tuple    = ('bind_theme',)                                                           
    _unique_constants : tuple    = ('mvTheme', 'mvThemeCat_Core', 'mvThemeCat_Plots', 'mvThemeCat_Nodes')    
    _command          : Callable = dearpygui.add_theme                                                       

    def __init__(
        self                           ,
        label             : str  = None,
        user_data         : Any  = None,
        use_internal_label: bool = True,
        **kwargs                       ,
    ) -> None:
        super().__init__(
            label=label,
            user_data=user_data,
            use_internal_label=use_internal_label,
            **kwargs,
        )


class ThemeComponent(Item):
    """Adds a theme component.
    
    	Args:
    		item_type (int, optional): 
    		label (str, optional): Overrides 'name' as label.
    		user_data (Any, optional): User data for callbacks
    		use_internal_label (bool, optional): Use generated internal label instead of user specified (appends ### uuid).
    		tag (Union[int, str], optional): Unique id used to programmatically refer to the item.If label is unused this will be the label.
    		parent (Union[int, str], optional): Parent to add this item to. (runtime adding)
    		before (Union[int, str], optional): This item will be displayed before the specified item in the parent.
    		enabled_state (bool, optional): 
    		id (Union[int, str], optional): (deprecated) 
    	Returns:
    		Union[int, str]
    """

    label             : str      = ItemAttribute("configuration", "get_item_config", "set_item_config", None)
    user_data         : Any      = ItemAttribute("configuration", "get_item_config", "set_item_config", None)
    use_internal_label: bool     = ItemAttribute("configuration", "get_item_config", "set_item_config", None)
    enabled_state     : bool     = ItemAttribute("configuration", "get_item_config", "set_item_config", None)

    _is_container     : bool     = True                                                                      
    _is_root_item     : bool     = False                                                                     
    _is_value_able    : bool     = False                                                                     
    _unique_parents   : tuple    = ('Theme',)                                                                
    _unique_children  : tuple    = ('ThemeColor', 'ThemeStyle')                                              
    _unique_commands  : tuple    = ()                                                                        
    _unique_constants : tuple    = ('mvThemeComponent',)                                                     
    _command          : Callable = dearpygui.add_theme_component                                             

    def __init__(
        self                                      ,
        item_type         : int             = 0   ,
        label             : str             = None,
        user_data         : Any             = None,
        use_internal_label: bool            = True,
        parent            : Union[int, str] = 0   ,
        before            : Union[int, str] = 0   ,
        enabled_state     : bool            = True,
        **kwargs                                  ,
    ) -> None:
        super().__init__(
            item_type=item_type,
            label=label,
            user_data=user_data,
            use_internal_label=use_internal_label,
            parent=parent,
            before=before,
            enabled_state=enabled_state,
            **kwargs,
        )


class ThemeColor(Item):
    """Adds a theme color.
    
    	Args:
    		target (int, optional): 
    		value (Union[List[int], Tuple[int, ...]], optional): 
    		label (str, optional): Overrides 'name' as label.
    		user_data (Any, optional): User data for callbacks
    		use_internal_label (bool, optional): Use generated internal label instead of user specified (appends ### uuid).
    		tag (Union[int, str], optional): Unique id used to programmatically refer to the item.If label is unused this will be the label.
    		parent (Union[int, str], optional): Parent to add this item to. (runtime adding)
    		category (int, optional): Options include mvThemeCat_Core, mvThemeCat_Plots, mvThemeCat_Nodes.
    		id (Union[int, str], optional): (deprecated) 
    	Returns:
    		Union[int, str]
    """

    target            : int                               = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    value             : Union[List[int], Tuple[int, ...]] = ItemAttribute('configuration', 'get_item_value', 'set_item_value', 'default_value')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    label             : str                               = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    user_data         : Any                               = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    use_internal_label: bool                              = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    category          : int                               = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

    _is_container     : bool                              = False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    _is_root_item     : bool                              = False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    _is_value_able    : bool                              = True                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    _unique_parents   : tuple                             = ('ThemeComponent', 'TemplateRegistry')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    _unique_children  : tuple                             = ()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    _unique_commands  : tuple                             = ()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    _unique_constants : tuple                             = ('mvThemeColor', 'mvThemeCol_Text', 'mvThemeCol_TextDisabled', 'mvThemeCol_WindowBg', 'mvThemeCol_ChildBg', 'mvThemeCol_Border', 'mvThemeCol_PopupBg', 'mvThemeCol_BorderShadow', 'mvThemeCol_FrameBg', 'mvThemeCol_FrameBgHovered', 'mvThemeCol_FrameBgActive', 'mvThemeCol_TitleBg', 'mvThemeCol_TitleBgActive', 'mvThemeCol_TitleBgCollapsed', 'mvThemeCol_MenuBarBg', 'mvThemeCol_ScrollbarBg', 'mvThemeCol_ScrollbarGrab', 'mvThemeCol_ScrollbarGrabHovered', 'mvThemeCol_ScrollbarGrabActive', 'mvThemeCol_CheckMark', 'mvThemeCol_SliderGrab', 'mvThemeCol_SliderGrabActive', 'mvThemeCol_Button', 'mvThemeCol_ButtonHovered', 'mvThemeCol_ButtonActive', 'mvThemeCol_Header', 'mvThemeCol_HeaderHovered', 'mvThemeCol_HeaderActive', 'mvThemeCol_Separator', 'mvThemeCol_SeparatorHovered', 'mvThemeCol_SeparatorActive', 'mvThemeCol_ResizeGrip', 'mvThemeCol_ResizeGripHovered', 'mvThemeCol_ResizeGripActive', 'mvThemeCol_Tab', 'mvThemeCol_TabHovered', 'mvThemeCol_TabActive', 'mvThemeCol_TabUnfocused', 'mvThemeCol_TabUnfocusedActive', 'mvThemeCol_DockingPreview', 'mvThemeCol_DockingEmptyBg', 'mvThemeCol_PlotLines', 'mvThemeCol_PlotLinesHovered', 'mvThemeCol_PlotHistogram', 'mvThemeCol_PlotHistogramHovered', 'mvThemeCol_TableHeaderBg', 'mvThemeCol_TableBorderStrong', 'mvThemeCol_TableBorderLight', 'mvThemeCol_TableRowBg', 'mvThemeCol_TableRowBgAlt', 'mvThemeCol_TextSelectedBg', 'mvThemeCol_DragDropTarget', 'mvThemeCol_NavHighlight', 'mvThemeCol_NavWindowingHighlight', 'mvThemeCol_NavWindowingDimBg', 'mvThemeCol_ModalWindowDimBg', 'mvPlotCol_Line', 'mvPlotCol_Fill', 'mvPlotCol_MarkerOutline', 'mvPlotCol_MarkerFill', 'mvPlotCol_ErrorBar', 'mvPlotCol_FrameBg', 'mvPlotCol_PlotBg', 'mvPlotCol_PlotBorder', 'mvPlotCol_LegendBg', 'mvPlotCol_LegendBorder', 'mvPlotCol_LegendText', 'mvPlotCol_TitleText', 'mvPlotCol_InlayText', 'mvPlotCol_XAxis', 'mvPlotCol_XAxisGrid', 'mvPlotCol_YAxis', 'mvPlotCol_YAxisGrid', 'mvPlotCol_YAxis2', 'mvPlotCol_YAxisGrid2', 'mvPlotCol_YAxis3', 'mvPlotCol_YAxisGrid3', 'mvPlotCol_Selection', 'mvPlotCol_Query', 'mvPlotCol_Crosshairs', 'mvNodeCol_NodeBackground', 'mvNodeCol_NodeBackgroundHovered', 'mvNodeCol_NodeBackgroundSelected', 'mvNodeCol_NodeOutline', 'mvNodeCol_TitleBar', 'mvNodeCol_TitleBarHovered', 'mvNodeCol_TitleBarSelected', 'mvNodeCol_Link', 'mvNodeCol_LinkHovered', 'mvNodeCol_LinkSelected', 'mvNodeCol_Pin', 'mvNodeCol_PinHovered', 'mvNodeCol_BoxSelector', 'mvNodeCol_BoxSelectorOutline', 'mvNodeCol_GridBackground', 'mvNodeCol_GridLine')
    _command          : Callable                          = dearpygui.add_theme_color                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

    def __init__(
        self                                                                  ,
        target            : int                               = 0             ,
        value             : Union[List[int], Tuple[int, ...]] = (0, 0, 0, 255),
        label             : str                               = None          ,
        user_data         : Any                               = None          ,
        use_internal_label: bool                              = True          ,
        parent            : Union[int, str]                   = 0             ,
        category          : int                               = 0             ,
        **kwargs                                                              ,
    ) -> None:
        super().__init__(
            target=target,
            value=value,
            label=label,
            user_data=user_data,
            use_internal_label=use_internal_label,
            parent=parent,
            category=category,
            **kwargs,
        )


class ThemeStyle(Item):
    """Adds a theme style.
    
    	Args:
    		target (int, optional): 
    		x (float, optional): 
    		y (float, optional): 
    		label (str, optional): Overrides 'name' as label.
    		user_data (Any, optional): User data for callbacks
    		use_internal_label (bool, optional): Use generated internal label instead of user specified (appends ### uuid).
    		tag (Union[int, str], optional): Unique id used to programmatically refer to the item.If label is unused this will be the label.
    		parent (Union[int, str], optional): Parent to add this item to. (runtime adding)
    		category (int, optional): Options include mvThemeCat_Core, mvThemeCat_Plots, mvThemeCat_Nodes.
    		id (Union[int, str], optional): (deprecated) 
    	Returns:
    		Union[int, str]
    """

    target            : int      = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    x                 : float    = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    y                 : float    = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    label             : str      = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    user_data         : Any      = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    use_internal_label: bool     = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    category          : int      = ItemAttribute("configuration", "get_item_config", "set_item_config", None)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

    _is_container     : bool     = False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    _is_root_item     : bool     = False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    _is_value_able    : bool     = True                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    _unique_parents   : tuple    = ('ThemeComponent', 'TemplateRegistry')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    _unique_children  : tuple    = ()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    _unique_commands  : tuple    = ()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    _unique_constants : tuple    = ('mvThemeStyle', 'mvStyleVar_Alpha', 'mvStyleVar_WindowPadding', 'mvStyleVar_WindowRounding', 'mvStyleVar_WindowBorderSize', 'mvStyleVar_WindowMinSize', 'mvStyleVar_WindowTitleAlign', 'mvStyleVar_ChildRounding', 'mvStyleVar_ChildBorderSize', 'mvStyleVar_PopupRounding', 'mvStyleVar_PopupBorderSize', 'mvStyleVar_FramePadding', 'mvStyleVar_FrameRounding', 'mvStyleVar_FrameBorderSize', 'mvStyleVar_ItemSpacing', 'mvStyleVar_ItemInnerSpacing', 'mvStyleVar_IndentSpacing', 'mvStyleVar_CellPadding', 'mvStyleVar_ScrollbarSize', 'mvStyleVar_ScrollbarRounding', 'mvStyleVar_GrabMinSize', 'mvStyleVar_GrabRounding', 'mvStyleVar_TabRounding', 'mvStyleVar_ButtonTextAlign', 'mvStyleVar_SelectableTextAlign', 'mvPlotStyleVar_LineWeight', 'mvPlotStyleVar_Marker', 'mvPlotStyleVar_MarkerSize', 'mvPlotStyleVar_MarkerWeight', 'mvPlotStyleVar_FillAlpha', 'mvPlotStyleVar_ErrorBarSize', 'mvPlotStyleVar_ErrorBarWeight', 'mvPlotStyleVar_DigitalBitHeight', 'mvPlotStyleVar_DigitalBitGap', 'mvPlotStyleVar_PlotBorderSize', 'mvPlotStyleVar_MinorAlpha', 'mvPlotStyleVar_MajorTickLen', 'mvPlotStyleVar_MinorTickLen', 'mvPlotStyleVar_MajorTickSize', 'mvPlotStyleVar_MinorTickSize', 'mvPlotStyleVar_MajorGridSize', 'mvPlotStyleVar_MinorGridSize', 'mvPlotStyleVar_PlotPadding', 'mvPlotStyleVar_LabelPadding', 'mvPlotStyleVar_LegendPadding', 'mvPlotStyleVar_LegendInnerPadding', 'mvPlotStyleVar_LegendSpacing', 'mvPlotStyleVar_MousePosPadding', 'mvPlotStyleVar_AnnotationPadding', 'mvPlotStyleVar_FitPadding', 'mvPlotStyleVar_PlotDefaultSize', 'mvPlotStyleVar_PlotMinSize', 'mvNodeStyleVar_GridSpacing', 'mvNodeStyleVar_NodeCornerRounding', 'mvNodeStyleVar_NodePaddingHorizontal', 'mvNodeStyleVar_NodePaddingVertical', 'mvNodeStyleVar_NodeBorderThickness', 'mvNodeStyleVar_LinkThickness', 'mvNodeStyleVar_LinkLineSegmentsPerLength', 'mvNodeStyleVar_LinkHoverDistance', 'mvNodeStyleVar_PinCircleRadius', 'mvNodeStyleVar_PinQuadSideLength', 'mvNodeStyleVar_PinTriangleSideLength', 'mvNodeStyleVar_PinLineThickness', 'mvNodeStyleVar_PinHoverRadius', 'mvNodeStyleVar_PinOffset')
    _command          : Callable = dearpygui.add_theme_style                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

    def __init__(
        self                                      ,
        target            : int             = 0   ,
        x                 : float           = 1.0 ,
        y                 : float           = -1.0,
        label             : str             = None,
        user_data         : Any             = None,
        use_internal_label: bool            = True,
        parent            : Union[int, str] = 0   ,
        category          : int             = 0   ,
        **kwargs                                  ,
    ) -> None:
        super().__init__(
            target=target,
            x=x,
            y=y,
            label=label,
            user_data=user_data,
            use_internal_label=use_internal_label,
            parent=parent,
            category=category,
            **kwargs,
        )
