import sys as _sys
if "dearpygui" in _sys.modules:
    import warnings as _warnings
    _warnings.warn("`dearpypixl` should be imported before `dearpygui`", stacklevel=2)
    del _warnings
del _sys


from dearpypixl.application import Application as Application
from dearpypixl.viewport import Viewport as Viewport
from dearpypixl.core.protocols import mvBuffer as mvBuffer
from dearpypixl.core.protocols import mvVec4 as mvVec4
from dearpypixl.core.protocols import mvMat4 as mvMat4
from dearpypixl.items import *

from dearpygui import _dearpygui
from dearpygui.dearpygui import (
    run_callbacks as run_callbacks,
    get_major_version as get_major_version,
    get_minor_version as get_minor_version,
    get_dearpygui_version as get_dearpygui_version,
    configure_item as configure_item,
    configure_app as configure_app,
    configure_viewport as configure_viewport,
    start_dearpygui as start_dearpygui,
    show_style_editor as show_style_editor,
    show_metrics as show_metrics,
    show_about as show_about,
    show_debug as show_debug,
    show_documentation as show_documentation,
    show_font_manager as show_font_manager,
    show_item_registry as show_item_registry,
    get_item_slot as get_item_slot,
    is_item_container as is_item_container,
    get_item_parent as get_item_parent,
    get_item_children as get_item_children,
    get_item_type as get_item_type,
    get_item_theme as get_item_theme,
    get_item_font as get_item_font,
    get_item_disabled_theme as get_item_disabled_theme,
    enable_item as enable_item,
    disable_item as disable_item,
    set_item_label as set_item_label,
    set_item_source as set_item_source,
    set_item_pos as set_item_pos,
    set_item_width as set_item_width,
    set_item_height as set_item_height,
    set_item_indent as set_item_indent,
    set_item_track_offset as set_item_track_offset,
    set_item_payload_type as set_item_payload_type,
    set_item_callback as set_item_callback,
    set_item_drag_callback as set_item_drag_callback,
    set_item_drop_callback as set_item_drop_callback,
    track_item as track_item,
    untrack_item as untrack_item,
    set_item_user_data as set_item_user_data,
    show_item as show_item,
    hide_item as hide_item,
    get_item_label as get_item_label,
    get_item_filter_key as get_item_filter_key,
    is_item_tracked as is_item_tracked,
    is_item_search_delayed as is_item_search_delayed,
    get_item_indent as get_item_indent,
    get_item_track_offset as get_item_track_offset,
    get_item_width as get_item_width,
    get_item_height as get_item_height,
    get_item_callback as get_item_callback,
    get_item_drag_callback as get_item_drag_callback,
    get_item_drop_callback as get_item_drop_callback,
    get_item_user_data as get_item_user_data,
    get_item_source as get_item_source,
    is_item_hovered as is_item_hovered,
    is_item_active as is_item_active,
    is_item_focused as is_item_focused,
    is_item_clicked as is_item_clicked,
    is_item_left_clicked as is_item_left_clicked,
    is_item_right_clicked as is_item_right_clicked,
    is_item_middle_clicked as is_item_middle_clicked,
    is_item_visible as is_item_visible,
    is_item_edited as is_item_edited,
    is_item_activated as is_item_activated,
    is_item_deactivated as is_item_deactivated,
    is_item_deactivated_after_edit as is_item_deactivated_after_edit,
    is_item_toggled_open as is_item_toggled_open,
    is_item_ok as is_item_ok,
    is_item_shown as is_item_shown,
    is_item_enabled as is_item_enabled,
    get_item_pos as get_item_pos,
    get_available_content_region as get_available_content_region,
    get_item_rect_size as get_item_rect_size,
    get_item_rect_min as get_item_rect_min,
    get_item_rect_max as get_item_rect_max,
    set_viewport_clear_color as set_viewport_clear_color,
    set_viewport_small_icon as set_viewport_small_icon,
    set_viewport_large_icon as set_viewport_large_icon,
    set_viewport_pos as set_viewport_pos,
    set_viewport_width as set_viewport_width,
    set_viewport_height as set_viewport_height,
    set_viewport_min_width as set_viewport_min_width,
    set_viewport_max_width as set_viewport_max_width,
    set_viewport_min_height as set_viewport_min_height,
    set_viewport_max_height as set_viewport_max_height,
    set_viewport_title as set_viewport_title,
    set_viewport_always_top as set_viewport_always_top,
    set_viewport_resizable as set_viewport_resizable,
    set_viewport_vsync as set_viewport_vsync,
    set_viewport_decorated as set_viewport_decorated,
    get_viewport_clear_color as get_viewport_clear_color,
    get_viewport_pos as get_viewport_pos,
    get_viewport_width as get_viewport_width,
    get_viewport_client_width as get_viewport_client_width,
    get_viewport_client_height as get_viewport_client_height,
    get_viewport_height as get_viewport_height,
    get_viewport_min_width as get_viewport_min_width,
    get_viewport_max_width as get_viewport_max_width,
    get_viewport_min_height as get_viewport_min_height,
    get_viewport_max_height as get_viewport_max_height,
    get_viewport_title as get_viewport_title,
    is_viewport_always_top as is_viewport_always_top,
    is_viewport_resizable as is_viewport_resizable,
    is_viewport_vsync_on as is_viewport_vsync_on,
    is_viewport_decorated as is_viewport_decorated,
    apply_transform as apply_transform,
    bind_colormap as bind_colormap,
    bind_font as bind_font,
    bind_item_font as bind_item_font,
    bind_item_handler_registry as bind_item_handler_registry,
    bind_item_theme as bind_item_theme,
    bind_theme as bind_theme,
    capture_next_item as capture_next_item,
    clear_selected_links as clear_selected_links,
    clear_selected_nodes as clear_selected_nodes,
    create_context as create_context,
    create_fps_matrix as create_fps_matrix,
    create_lookat_matrix as create_lookat_matrix,
    create_orthographic_matrix as create_orthographic_matrix,
    create_perspective_matrix as create_perspective_matrix,
    create_rotation_matrix as create_rotation_matrix,
    create_scale_matrix as create_scale_matrix,
    create_translation_matrix as create_translation_matrix,
    create_viewport as create_viewport,
    delete_item as delete_item,
    destroy_context as destroy_context,
    does_alias_exist as does_alias_exist,
    does_item_exist as does_item_exist,
    empty_container_stack as empty_container_stack,
    fit_axis_data as fit_axis_data,
    focus_item as focus_item,
    generate_uuid as generate_uuid,
    get_active_window as get_active_window,
    get_alias_id as get_alias_id,
    get_aliases as get_aliases,
    get_all_items as get_all_items,
    get_app_configuration as get_app_configuration,
    get_axis_limits as get_axis_limits,
    get_callback_queue as get_callback_queue,
    get_clipboard_text as get_clipboard_text,
    get_colormap_color as get_colormap_color,
    get_delta_time as get_delta_time,
    get_drawing_mouse_pos as get_drawing_mouse_pos,
    get_file_dialog_info as get_file_dialog_info,
    get_focused_item as get_focused_item,
    get_frame_count as get_frame_count,
    get_frame_rate as get_frame_rate,
    get_global_font_scale as get_global_font_scale,
    get_item_alias as get_item_alias,
    get_item_configuration as get_item_configuration,
    get_item_info as get_item_info,
    get_item_state as get_item_state,
    get_item_types as get_item_types,
    get_mouse_drag_delta as get_mouse_drag_delta,
    get_mouse_pos as get_mouse_pos,
    get_platform as get_platform,
    get_plot_mouse_pos as get_plot_mouse_pos,
    get_plot_query_rects as get_plot_query_rects,
    get_selected_links as get_selected_links,
    get_selected_nodes as get_selected_nodes,
    get_text_size as get_text_size,
    get_total_time as get_total_time,
    get_value as get_value,
    get_values as get_values,
    get_viewport_configuration as get_viewport_configuration,
    get_windows as get_windows,
    get_x_scroll as get_x_scroll,
    get_x_scroll_max as get_x_scroll_max,
    get_y_scroll as get_y_scroll,
    get_y_scroll_max as get_y_scroll_max,
    highlight_table_cell as highlight_table_cell,
    highlight_table_column as highlight_table_column,
    highlight_table_row as highlight_table_row,
    is_dearpygui_running as is_dearpygui_running,
    is_key_down as is_key_down,
    is_key_pressed as is_key_pressed,
    is_key_released as is_key_released,
    is_mouse_button_clicked as is_mouse_button_clicked,
    is_mouse_button_double_clicked as is_mouse_button_double_clicked,
    is_mouse_button_down as is_mouse_button_down,
    is_mouse_button_dragging as is_mouse_button_dragging,
    is_mouse_button_released as is_mouse_button_released,
    is_table_cell_highlighted as is_table_cell_highlighted,
    is_table_column_highlighted as is_table_column_highlighted,
    is_table_row_highlighted as is_table_row_highlighted,
    is_viewport_ok as is_viewport_ok,
    last_container as last_container,
    last_item as last_item,
    last_root as last_root,
    load_image as load_image,
    lock_mutex as lock_mutex,
    maximize_viewport as maximize_viewport,
    minimize_viewport as minimize_viewport,
    move_item as move_item,
    move_item_down as move_item_down,
    move_item_up as move_item_up,
    output_frame_buffer as output_frame_buffer,
    pop_container_stack as pop_container_stack,
    push_container_stack as push_container_stack,
    remove_alias as remove_alias,
    render_dearpygui_frame as render_dearpygui_frame,
    reorder_items as reorder_items,
    reset_axis_limits_constraints as reset_axis_limits_constraints,
    reset_axis_ticks as reset_axis_ticks,
    reset_axis_zoom_constraints as reset_axis_zoom_constraints,
    reset_pos as reset_pos,
    sample_colormap as sample_colormap,
    save_image as save_image,
    save_init_file as save_init_file,
    set_axis_limits as set_axis_limits,
    set_axis_limits_auto as set_axis_limits_auto,
    set_axis_limits_constraints as set_axis_limits_constraints,
    set_axis_ticks as set_axis_ticks,
    set_axis_zoom_constraints as set_axis_zoom_constraints,
    set_clip_space as set_clip_space,
    set_clipboard_text as set_clipboard_text,
    set_exit_callback as set_exit_callback,
    set_frame_callback as set_frame_callback,
    set_global_font_scale as set_global_font_scale,
    set_item_alias as set_item_alias,
    set_item_children as set_item_children,
    set_primary_window as set_primary_window,
    set_table_row_color as set_table_row_color,
    set_value as set_value,
    set_viewport_resize_callback as set_viewport_resize_callback,
    set_x_scroll as set_x_scroll,
    set_y_scroll as set_y_scroll,
    setup_dearpygui as setup_dearpygui,
    show_imgui_demo as show_imgui_demo,
    show_implot_demo as show_implot_demo,
    show_item_debug as show_item_debug,
    show_tool as show_tool,
    show_viewport as show_viewport,
    split_frame as split_frame,
    stop_dearpygui as stop_dearpygui,
    toggle_viewport_fullscreen as toggle_viewport_fullscreen,
    top_container_stack as top_container_stack,
    unhighlight_table_cell as unhighlight_table_cell,
    unhighlight_table_column as unhighlight_table_column,
    unhighlight_table_row as unhighlight_table_row,
    unlock_mutex as unlock_mutex,
    unset_table_row_color as unset_table_row_color,
    unstage as unstage,
)


class _mutex:
    __slots__ = ()

    acquire = _dearpygui.lock_mutex
    release = _dearpygui.unlock_mutex

    def __enter__(self, /) -> None:
        self.acquire()  # type: ignore

    def __exit__(self, exc_type=None, error=None, traceback=None, /) -> None:
        self.release()  # type: ignore

mutex = _mutex()
