############################################################
# DearPyPixl Constants Library
#
# DearPyPixl version: 2.0.0
# DearPyGui version: 2.2.0
#
# NOTE: This file is automatically generated - changes may be
# overwritten.
############################################################
import enum as _enum

from dearpygui import _dearpygui




class DearPyGui(_enum.IntEnum):
    mvAll = _dearpygui.mvAll
    mvAppUUID = _dearpygui.mvAppUUID
    mvFontAtlas = _dearpygui.mvFontAtlas
    mvInvalidUUID = _dearpygui.mvInvalidUUID
    mvXAxis = _dearpygui.mvXAxis
    mvXAxis2 = _dearpygui.mvXAxis2
    mvXAxis3 = _dearpygui.mvXAxis3
    mvYAxis = _dearpygui.mvYAxis
    mvYAxis2 = _dearpygui.mvYAxis2
    mvYAxis3 = _dearpygui.mvYAxis3

mvAll = DearPyGui.mvAll
mvAppUUID = DearPyGui.mvAppUUID
mvFontAtlas = DearPyGui.mvFontAtlas
mvInvalidUUID = DearPyGui.mvInvalidUUID
mvXAxis = DearPyGui.mvXAxis
mvXAxis2 = DearPyGui.mvXAxis2
mvXAxis3 = DearPyGui.mvXAxis3
mvYAxis = DearPyGui.mvYAxis
mvYAxis2 = DearPyGui.mvYAxis2
mvYAxis3 = DearPyGui.mvYAxis3


class mvColorEdit(_enum.IntEnum):
    ALPHA_PREVIEW = _dearpygui.mvColorEdit_AlphaPreview
    ALPHA_PREVIEW_HALF = _dearpygui.mvColorEdit_AlphaPreviewHalf
    ALPHA_PREVIEW_NONE = _dearpygui.mvColorEdit_AlphaPreviewNone
    FLOAT = _dearpygui.mvColorEdit_float
    HEX = _dearpygui.mvColorEdit_hex
    HSV = _dearpygui.mvColorEdit_hsv
    INPUT_HSV = _dearpygui.mvColorEdit_input_hsv
    INPUT_RGB = _dearpygui.mvColorEdit_input_rgb
    RGB = _dearpygui.mvColorEdit_rgb
    UINT8 = _dearpygui.mvColorEdit_uint8

mvColorEdit_AlphaPreview = mvColorEdit.ALPHA_PREVIEW
mvColorEdit_AlphaPreviewHalf = mvColorEdit.ALPHA_PREVIEW_HALF
mvColorEdit_AlphaPreviewNone = mvColorEdit.ALPHA_PREVIEW_NONE
mvColorEdit_float = mvColorEdit.FLOAT
mvColorEdit_hex = mvColorEdit.HEX
mvColorEdit_hsv = mvColorEdit.HSV
mvColorEdit_input_hsv = mvColorEdit.INPUT_HSV
mvColorEdit_input_rgb = mvColorEdit.INPUT_RGB
mvColorEdit_rgb = mvColorEdit.RGB
mvColorEdit_uint8 = mvColorEdit.UINT8


class mvColorPicker(_enum.IntEnum):
    BAR = _dearpygui.mvColorPicker_bar
    WHEEL = _dearpygui.mvColorPicker_wheel

mvColorPicker_bar = mvColorPicker.BAR
mvColorPicker_wheel = mvColorPicker.WHEEL


class mvComboHeight(_enum.IntEnum):
    LARGE = _dearpygui.mvComboHeight_Large
    LARGEST = _dearpygui.mvComboHeight_Largest
    REGULAR = _dearpygui.mvComboHeight_Regular
    SMALL = _dearpygui.mvComboHeight_Small

mvComboHeight_Large = mvComboHeight.LARGE
mvComboHeight_Largest = mvComboHeight.LARGEST
mvComboHeight_Regular = mvComboHeight.REGULAR
mvComboHeight_Small = mvComboHeight.SMALL


class mvCullMode(_enum.IntEnum):
    BACK = _dearpygui.mvCullMode_Back
    FRONT = _dearpygui.mvCullMode_Front
    NONE = _dearpygui.mvCullMode_None

mvCullMode_Back = mvCullMode.BACK
mvCullMode_Front = mvCullMode.FRONT
mvCullMode_None = mvCullMode.NONE


class mvDatePickerLevel(_enum.IntEnum):
    DAY = _dearpygui.mvDatePickerLevel_Day
    MONTH = _dearpygui.mvDatePickerLevel_Month
    YEAR = _dearpygui.mvDatePickerLevel_Year

mvDatePickerLevel_Day = mvDatePickerLevel.DAY
mvDatePickerLevel_Month = mvDatePickerLevel.MONTH
mvDatePickerLevel_Year = mvDatePickerLevel.YEAR


class mvDir(_enum.IntEnum):
    DOWN = _dearpygui.mvDir_Down
    LEFT = _dearpygui.mvDir_Left
    NONE = _dearpygui.mvDir_None
    RIGHT = _dearpygui.mvDir_Right
    UP = _dearpygui.mvDir_Up

mvDir_Down = mvDir.DOWN
mvDir_Left = mvDir.LEFT
mvDir_None = mvDir.NONE
mvDir_Right = mvDir.RIGHT
mvDir_Up = mvDir.UP


class mvEventType(_enum.IntEnum):
    ENTER = _dearpygui.mvEventType_Enter
    LEAVE = _dearpygui.mvEventType_Leave
    OFF = _dearpygui.mvEventType_Off
    ON = _dearpygui.mvEventType_On

mvEventType_Enter = mvEventType.ENTER
mvEventType_Leave = mvEventType.LEAVE
mvEventType_Off = mvEventType.OFF
mvEventType_On = mvEventType.ON


class mvFontRangeHint(_enum.IntEnum):
    CHINESE_FULL = _dearpygui.mvFontRangeHint_Chinese_Full
    CHINESE_SIMPLIFIED_COMMON = _dearpygui.mvFontRangeHint_Chinese_Simplified_Common
    CYRILLIC = _dearpygui.mvFontRangeHint_Cyrillic
    DEFAULT = _dearpygui.mvFontRangeHint_Default
    JAPANESE = _dearpygui.mvFontRangeHint_Japanese
    KOREAN = _dearpygui.mvFontRangeHint_Korean
    THAI = _dearpygui.mvFontRangeHint_Thai
    VIETNAMESE = _dearpygui.mvFontRangeHint_Vietnamese

mvFontRangeHint_Chinese_Full = mvFontRangeHint.CHINESE_FULL
mvFontRangeHint_Chinese_Simplified_Common = mvFontRangeHint.CHINESE_SIMPLIFIED_COMMON
mvFontRangeHint_Cyrillic = mvFontRangeHint.CYRILLIC
mvFontRangeHint_Default = mvFontRangeHint.DEFAULT
mvFontRangeHint_Japanese = mvFontRangeHint.JAPANESE
mvFontRangeHint_Korean = mvFontRangeHint.KOREAN
mvFontRangeHint_Thai = mvFontRangeHint.THAI
mvFontRangeHint_Vietnamese = mvFontRangeHint.VIETNAMESE


class mvFormat(_enum.IntEnum):
    FLOAT_RGB = _dearpygui.mvFormat_Float_rgb
    FLOAT_RGBA = _dearpygui.mvFormat_Float_rgba

mvFormat_Float_rgb = mvFormat.FLOAT_RGB
mvFormat_Float_rgba = mvFormat.FLOAT_RGBA


class mvLoadInd(_enum.IntEnum):
    DOTTED_CIRCLE = _dearpygui.mvLoadInd_DottedCircle
    RING = _dearpygui.mvLoadInd_Ring

mvLoadInd_DottedCircle = mvLoadInd.DOTTED_CIRCLE
mvLoadInd_Ring = mvLoadInd.RING


class mvNodeCol(_enum.IntEnum):
    BOX_SELECTOR = _dearpygui.mvNodeCol_BoxSelector
    BOX_SELECTOR_OUTLINE = _dearpygui.mvNodeCol_BoxSelectorOutline
    GRID_BACKGROUND = _dearpygui.mvNodeCol_GridBackground
    GRID_LINE = _dearpygui.mvNodeCol_GridLine
    GRID_LINE_PRIMARY = _dearpygui.mvNodesCol_GridLinePrimary
    LINK = _dearpygui.mvNodeCol_Link
    LINK_HOVERED = _dearpygui.mvNodeCol_LinkHovered
    LINK_SELECTED = _dearpygui.mvNodeCol_LinkSelected
    MINI_MAP_BACKGROUND = _dearpygui.mvNodesCol_MiniMapBackground
    MINI_MAP_BACKGROUND_HOVERED = _dearpygui.mvNodesCol_MiniMapBackgroundHovered
    MINI_MAP_CANVAS = _dearpygui.mvNodesCol_MiniMapCanvas
    MINI_MAP_CANVAS_OUTLINE = _dearpygui.mvNodesCol_MiniMapCanvasOutline
    MINI_MAP_LINK = _dearpygui.mvNodesCol_MiniMapLink
    MINI_MAP_LINK_SELECTED = _dearpygui.mvNodesCol_MiniMapLinkSelected
    MINI_MAP_NODE_BACKGROUND = _dearpygui.mvNodesCol_MiniMapNodeBackground
    MINI_MAP_NODE_BACKGROUND_HOVERED = _dearpygui.mvNodesCol_MiniMapNodeBackgroundHovered
    MINI_MAP_NODE_BACKGROUND_SELECTED = _dearpygui.mvNodesCol_MiniMapNodeBackgroundSelected
    MINI_MAP_NODE_OUTLINE = _dearpygui.mvNodesCol_MiniMapNodeOutline
    MINI_MAP_OUTLINE = _dearpygui.mvNodesCol_MiniMapOutline
    MINI_MAP_OUTLINE_HOVERED = _dearpygui.mvNodesCol_MiniMapOutlineHovered
    NODE_BACKGROUND = _dearpygui.mvNodeCol_NodeBackground
    NODE_BACKGROUND_HOVERED = _dearpygui.mvNodeCol_NodeBackgroundHovered
    NODE_BACKGROUND_SELECTED = _dearpygui.mvNodeCol_NodeBackgroundSelected
    NODE_OUTLINE = _dearpygui.mvNodeCol_NodeOutline
    PIN = _dearpygui.mvNodeCol_Pin
    PIN_HOVERED = _dearpygui.mvNodeCol_PinHovered
    TITLE_BAR = _dearpygui.mvNodeCol_TitleBar
    TITLE_BAR_HOVERED = _dearpygui.mvNodeCol_TitleBarHovered
    TITLE_BAR_SELECTED = _dearpygui.mvNodeCol_TitleBarSelected

mvNodeCol_BoxSelector = mvNodeCol.BOX_SELECTOR
mvNodeCol_BoxSelectorOutline = mvNodeCol.BOX_SELECTOR_OUTLINE
mvNodeCol_GridBackground = mvNodeCol.GRID_BACKGROUND
mvNodeCol_GridLine = mvNodeCol.GRID_LINE
mvNodesCol_GridLinePrimary = mvNodeCol.GRID_LINE_PRIMARY
mvNodeCol_Link = mvNodeCol.LINK
mvNodeCol_LinkHovered = mvNodeCol.LINK_HOVERED
mvNodeCol_LinkSelected = mvNodeCol.LINK_SELECTED
mvNodesCol_MiniMapBackground = mvNodeCol.MINI_MAP_BACKGROUND
mvNodesCol_MiniMapBackgroundHovered = mvNodeCol.MINI_MAP_BACKGROUND_HOVERED
mvNodesCol_MiniMapCanvas = mvNodeCol.MINI_MAP_CANVAS
mvNodesCol_MiniMapCanvasOutline = mvNodeCol.MINI_MAP_CANVAS_OUTLINE
mvNodesCol_MiniMapLink = mvNodeCol.MINI_MAP_LINK
mvNodesCol_MiniMapLinkSelected = mvNodeCol.MINI_MAP_LINK_SELECTED
mvNodesCol_MiniMapNodeBackground = mvNodeCol.MINI_MAP_NODE_BACKGROUND
mvNodesCol_MiniMapNodeBackgroundHovered = mvNodeCol.MINI_MAP_NODE_BACKGROUND_HOVERED
mvNodesCol_MiniMapNodeBackgroundSelected = mvNodeCol.MINI_MAP_NODE_BACKGROUND_SELECTED
mvNodesCol_MiniMapNodeOutline = mvNodeCol.MINI_MAP_NODE_OUTLINE
mvNodesCol_MiniMapOutline = mvNodeCol.MINI_MAP_OUTLINE
mvNodesCol_MiniMapOutlineHovered = mvNodeCol.MINI_MAP_OUTLINE_HOVERED
mvNodeCol_NodeBackground = mvNodeCol.NODE_BACKGROUND
mvNodeCol_NodeBackgroundHovered = mvNodeCol.NODE_BACKGROUND_HOVERED
mvNodeCol_NodeBackgroundSelected = mvNodeCol.NODE_BACKGROUND_SELECTED
mvNodeCol_NodeOutline = mvNodeCol.NODE_OUTLINE
mvNodeCol_Pin = mvNodeCol.PIN
mvNodeCol_PinHovered = mvNodeCol.PIN_HOVERED
mvNodeCol_TitleBar = mvNodeCol.TITLE_BAR
mvNodeCol_TitleBarHovered = mvNodeCol.TITLE_BAR_HOVERED
mvNodeCol_TitleBarSelected = mvNodeCol.TITLE_BAR_SELECTED


class mvNodeMiniMap(_enum.IntEnum):
    LOCATION_BOTTOM_LEFT = _dearpygui.mvNodeMiniMap_Location_BottomLeft
    LOCATION_BOTTOM_RIGHT = _dearpygui.mvNodeMiniMap_Location_BottomRight
    LOCATION_TOP_LEFT = _dearpygui.mvNodeMiniMap_Location_TopLeft
    LOCATION_TOP_RIGHT = _dearpygui.mvNodeMiniMap_Location_TopRight

mvNodeMiniMap_Location_BottomLeft = mvNodeMiniMap.LOCATION_BOTTOM_LEFT
mvNodeMiniMap_Location_BottomRight = mvNodeMiniMap.LOCATION_BOTTOM_RIGHT
mvNodeMiniMap_Location_TopLeft = mvNodeMiniMap.LOCATION_TOP_LEFT
mvNodeMiniMap_Location_TopRight = mvNodeMiniMap.LOCATION_TOP_RIGHT


class mvNodeStyleVar(_enum.IntEnum):
    GRID_SPACING = _dearpygui.mvNodeStyleVar_GridSpacing
    LINK_HOVER_DISTANCE = _dearpygui.mvNodeStyleVar_LinkHoverDistance
    LINK_LINE_SEGMENTS_PER_LENGTH = _dearpygui.mvNodeStyleVar_LinkLineSegmentsPerLength
    LINK_THICKNESS = _dearpygui.mvNodeStyleVar_LinkThickness
    MINI_MAP_OFFSET = _dearpygui.mvNodesStyleVar_MiniMapOffset
    MINI_MAP_PADDING = _dearpygui.mvNodesStyleVar_MiniMapPadding
    NODE_BORDER_THICKNESS = _dearpygui.mvNodeStyleVar_NodeBorderThickness
    NODE_CORNER_ROUNDING = _dearpygui.mvNodeStyleVar_NodeCornerRounding
    NODE_PADDING = _dearpygui.mvNodeStyleVar_NodePadding
    PIN_CIRCLE_RADIUS = _dearpygui.mvNodeStyleVar_PinCircleRadius
    PIN_HOVER_RADIUS = _dearpygui.mvNodeStyleVar_PinHoverRadius
    PIN_LINE_THICKNESS = _dearpygui.mvNodeStyleVar_PinLineThickness
    PIN_OFFSET = _dearpygui.mvNodeStyleVar_PinOffset
    PIN_QUAD_SIDE_LENGTH = _dearpygui.mvNodeStyleVar_PinQuadSideLength
    PIN_TRIANGLE_SIDE_LENGTH = _dearpygui.mvNodeStyleVar_PinTriangleSideLength

mvNodeStyleVar_GridSpacing = mvNodeStyleVar.GRID_SPACING
mvNodeStyleVar_LinkHoverDistance = mvNodeStyleVar.LINK_HOVER_DISTANCE
mvNodeStyleVar_LinkLineSegmentsPerLength = mvNodeStyleVar.LINK_LINE_SEGMENTS_PER_LENGTH
mvNodeStyleVar_LinkThickness = mvNodeStyleVar.LINK_THICKNESS
mvNodesStyleVar_MiniMapOffset = mvNodeStyleVar.MINI_MAP_OFFSET
mvNodesStyleVar_MiniMapPadding = mvNodeStyleVar.MINI_MAP_PADDING
mvNodeStyleVar_NodeBorderThickness = mvNodeStyleVar.NODE_BORDER_THICKNESS
mvNodeStyleVar_NodeCornerRounding = mvNodeStyleVar.NODE_CORNER_ROUNDING
mvNodeStyleVar_NodePadding = mvNodeStyleVar.NODE_PADDING
mvNodeStyleVar_PinCircleRadius = mvNodeStyleVar.PIN_CIRCLE_RADIUS
mvNodeStyleVar_PinHoverRadius = mvNodeStyleVar.PIN_HOVER_RADIUS
mvNodeStyleVar_PinLineThickness = mvNodeStyleVar.PIN_LINE_THICKNESS
mvNodeStyleVar_PinOffset = mvNodeStyleVar.PIN_OFFSET
mvNodeStyleVar_PinQuadSideLength = mvNodeStyleVar.PIN_QUAD_SIDE_LENGTH
mvNodeStyleVar_PinTriangleSideLength = mvNodeStyleVar.PIN_TRIANGLE_SIDE_LENGTH


class mvPlatform(_enum.IntEnum):
    APPLE = _dearpygui.mvPlatform_Apple
    LINUX = _dearpygui.mvPlatform_Linux
    WINDOWS = _dearpygui.mvPlatform_Windows

mvPlatform_Apple = mvPlatform.APPLE
mvPlatform_Linux = mvPlatform.LINUX
mvPlatform_Windows = mvPlatform.WINDOWS


class mvPlotBin(_enum.IntEnum):
    RICE = _dearpygui.mvPlotBin_Rice
    SCOTT = _dearpygui.mvPlotBin_Scott
    SQRT = _dearpygui.mvPlotBin_Sqrt
    STURGES = _dearpygui.mvPlotBin_Sturges

mvPlotBin_Rice = mvPlotBin.RICE
mvPlotBin_Scott = mvPlotBin.SCOTT
mvPlotBin_Sqrt = mvPlotBin.SQRT
mvPlotBin_Sturges = mvPlotBin.STURGES


class mvPlotCol(_enum.IntEnum):
    AXIS_BG = _dearpygui.mvPlotCol_AxisBg
    AXIS_BG_ACTIVE = _dearpygui.mvPlotCol_AxisBgActive
    AXIS_BG_HOVERED = _dearpygui.mvPlotCol_AxisBgHovered
    AXIS_GRID = _dearpygui.mvPlotCol_AxisGrid
    AXIS_TEXT = _dearpygui.mvPlotCol_AxisText
    CROSSHAIRS = _dearpygui.mvPlotCol_Crosshairs
    ERROR_BAR = _dearpygui.mvPlotCol_ErrorBar
    FILL = _dearpygui.mvPlotCol_Fill
    FRAME_BG = _dearpygui.mvPlotCol_FrameBg
    INLAY_TEXT = _dearpygui.mvPlotCol_InlayText
    LEGEND_BG = _dearpygui.mvPlotCol_LegendBg
    LEGEND_BORDER = _dearpygui.mvPlotCol_LegendBorder
    LEGEND_TEXT = _dearpygui.mvPlotCol_LegendText
    LINE = _dearpygui.mvPlotCol_Line
    MARKER_FILL = _dearpygui.mvPlotCol_MarkerFill
    MARKER_OUTLINE = _dearpygui.mvPlotCol_MarkerOutline
    PLOT_BG = _dearpygui.mvPlotCol_PlotBg
    PLOT_BORDER = _dearpygui.mvPlotCol_PlotBorder
    SELECTION = _dearpygui.mvPlotCol_Selection
    TITLE_TEXT = _dearpygui.mvPlotCol_TitleText

mvPlotCol_AxisBg = mvPlotCol.AXIS_BG
mvPlotCol_AxisBgActive = mvPlotCol.AXIS_BG_ACTIVE
mvPlotCol_AxisBgHovered = mvPlotCol.AXIS_BG_HOVERED
mvPlotCol_AxisGrid = mvPlotCol.AXIS_GRID
mvPlotCol_AxisText = mvPlotCol.AXIS_TEXT
mvPlotCol_Crosshairs = mvPlotCol.CROSSHAIRS
mvPlotCol_ErrorBar = mvPlotCol.ERROR_BAR
mvPlotCol_Fill = mvPlotCol.FILL
mvPlotCol_FrameBg = mvPlotCol.FRAME_BG
mvPlotCol_InlayText = mvPlotCol.INLAY_TEXT
mvPlotCol_LegendBg = mvPlotCol.LEGEND_BG
mvPlotCol_LegendBorder = mvPlotCol.LEGEND_BORDER
mvPlotCol_LegendText = mvPlotCol.LEGEND_TEXT
mvPlotCol_Line = mvPlotCol.LINE
mvPlotCol_MarkerFill = mvPlotCol.MARKER_FILL
mvPlotCol_MarkerOutline = mvPlotCol.MARKER_OUTLINE
mvPlotCol_PlotBg = mvPlotCol.PLOT_BG
mvPlotCol_PlotBorder = mvPlotCol.PLOT_BORDER
mvPlotCol_Selection = mvPlotCol.SELECTION
mvPlotCol_TitleText = mvPlotCol.TITLE_TEXT


class mvPlotColormap(_enum.IntEnum):
    BR_B_G = _dearpygui.mvPlotColormap_BrBG
    COOL = _dearpygui.mvPlotColormap_Cool
    DARK = _dearpygui.mvPlotColormap_Dark
    DEEP = _dearpygui.mvPlotColormap_Deep
    DEFAULT = _dearpygui.mvPlotColormap_Default
    GREYS = _dearpygui.mvPlotColormap_Greys
    HOT = _dearpygui.mvPlotColormap_Hot
    JET = _dearpygui.mvPlotColormap_Jet
    PAIRED = _dearpygui.mvPlotColormap_Paired
    PASTEL = _dearpygui.mvPlotColormap_Pastel
    PI_Y_G = _dearpygui.mvPlotColormap_PiYG
    PINK = _dearpygui.mvPlotColormap_Pink
    PLASMA = _dearpygui.mvPlotColormap_Plasma
    RD_BU = _dearpygui.mvPlotColormap_RdBu
    SPECTRAL = _dearpygui.mvPlotColormap_Spectral
    TWILIGHT = _dearpygui.mvPlotColormap_Twilight
    VIRIDIS = _dearpygui.mvPlotColormap_Viridis

mvPlotColormap_BrBG = mvPlotColormap.BR_B_G
mvPlotColormap_Cool = mvPlotColormap.COOL
mvPlotColormap_Dark = mvPlotColormap.DARK
mvPlotColormap_Deep = mvPlotColormap.DEEP
mvPlotColormap_Default = mvPlotColormap.DEFAULT
mvPlotColormap_Greys = mvPlotColormap.GREYS
mvPlotColormap_Hot = mvPlotColormap.HOT
mvPlotColormap_Jet = mvPlotColormap.JET
mvPlotColormap_Paired = mvPlotColormap.PAIRED
mvPlotColormap_Pastel = mvPlotColormap.PASTEL
mvPlotColormap_PiYG = mvPlotColormap.PI_Y_G
mvPlotColormap_Pink = mvPlotColormap.PINK
mvPlotColormap_Plasma = mvPlotColormap.PLASMA
mvPlotColormap_RdBu = mvPlotColormap.RD_BU
mvPlotColormap_Spectral = mvPlotColormap.SPECTRAL
mvPlotColormap_Twilight = mvPlotColormap.TWILIGHT
mvPlotColormap_Viridis = mvPlotColormap.VIRIDIS


class mvPlotMarker(_enum.IntEnum):
    ASTERISK = _dearpygui.mvPlotMarker_Asterisk
    CIRCLE = _dearpygui.mvPlotMarker_Circle
    CROSS = _dearpygui.mvPlotMarker_Cross
    DIAMOND = _dearpygui.mvPlotMarker_Diamond
    DOWN = _dearpygui.mvPlotMarker_Down
    LEFT = _dearpygui.mvPlotMarker_Left
    NONE = _dearpygui.mvPlotMarker_None
    PLUS = _dearpygui.mvPlotMarker_Plus
    RIGHT = _dearpygui.mvPlotMarker_Right
    SQUARE = _dearpygui.mvPlotMarker_Square
    UP = _dearpygui.mvPlotMarker_Up

mvPlotMarker_Asterisk = mvPlotMarker.ASTERISK
mvPlotMarker_Circle = mvPlotMarker.CIRCLE
mvPlotMarker_Cross = mvPlotMarker.CROSS
mvPlotMarker_Diamond = mvPlotMarker.DIAMOND
mvPlotMarker_Down = mvPlotMarker.DOWN
mvPlotMarker_Left = mvPlotMarker.LEFT
mvPlotMarker_None = mvPlotMarker.NONE
mvPlotMarker_Plus = mvPlotMarker.PLUS
mvPlotMarker_Right = mvPlotMarker.RIGHT
mvPlotMarker_Square = mvPlotMarker.SQUARE
mvPlotMarker_Up = mvPlotMarker.UP


class mvPlotScale(_enum.IntEnum):
    LINEAR = _dearpygui.mvPlotScale_Linear
    LOG10 = _dearpygui.mvPlotScale_Log10
    SYM_LOG = _dearpygui.mvPlotScale_SymLog
    TIME = _dearpygui.mvPlotScale_Time

mvPlotScale_Linear = mvPlotScale.LINEAR
mvPlotScale_Log10 = mvPlotScale.LOG10
mvPlotScale_SymLog = mvPlotScale.SYM_LOG
mvPlotScale_Time = mvPlotScale.TIME


class mvPlotStyleVar(_enum.IntEnum):
    ANNOTATION_PADDING = _dearpygui.mvPlotStyleVar_AnnotationPadding
    DIGITAL_BIT_GAP = _dearpygui.mvPlotStyleVar_DigitalBitGap
    DIGITAL_BIT_HEIGHT = _dearpygui.mvPlotStyleVar_DigitalBitHeight
    ERROR_BAR_SIZE = _dearpygui.mvPlotStyleVar_ErrorBarSize
    ERROR_BAR_WEIGHT = _dearpygui.mvPlotStyleVar_ErrorBarWeight
    FILL_ALPHA = _dearpygui.mvPlotStyleVar_FillAlpha
    FIT_PADDING = _dearpygui.mvPlotStyleVar_FitPadding
    LABEL_PADDING = _dearpygui.mvPlotStyleVar_LabelPadding
    LEGEND_INNER_PADDING = _dearpygui.mvPlotStyleVar_LegendInnerPadding
    LEGEND_PADDING = _dearpygui.mvPlotStyleVar_LegendPadding
    LEGEND_SPACING = _dearpygui.mvPlotStyleVar_LegendSpacing
    LINE_WEIGHT = _dearpygui.mvPlotStyleVar_LineWeight
    MAJOR_GRID_SIZE = _dearpygui.mvPlotStyleVar_MajorGridSize
    MAJOR_TICK_LEN = _dearpygui.mvPlotStyleVar_MajorTickLen
    MAJOR_TICK_SIZE = _dearpygui.mvPlotStyleVar_MajorTickSize
    MARKER = _dearpygui.mvPlotStyleVar_Marker
    MARKER_SIZE = _dearpygui.mvPlotStyleVar_MarkerSize
    MARKER_WEIGHT = _dearpygui.mvPlotStyleVar_MarkerWeight
    MINOR_ALPHA = _dearpygui.mvPlotStyleVar_MinorAlpha
    MINOR_GRID_SIZE = _dearpygui.mvPlotStyleVar_MinorGridSize
    MINOR_TICK_LEN = _dearpygui.mvPlotStyleVar_MinorTickLen
    MINOR_TICK_SIZE = _dearpygui.mvPlotStyleVar_MinorTickSize
    MOUSE_POS_PADDING = _dearpygui.mvPlotStyleVar_MousePosPadding
    PLOT_BORDER_SIZE = _dearpygui.mvPlotStyleVar_PlotBorderSize
    PLOT_DEFAULT_SIZE = _dearpygui.mvPlotStyleVar_PlotDefaultSize
    PLOT_MIN_SIZE = _dearpygui.mvPlotStyleVar_PlotMinSize
    PLOT_PADDING = _dearpygui.mvPlotStyleVar_PlotPadding

mvPlotStyleVar_AnnotationPadding = mvPlotStyleVar.ANNOTATION_PADDING
mvPlotStyleVar_DigitalBitGap = mvPlotStyleVar.DIGITAL_BIT_GAP
mvPlotStyleVar_DigitalBitHeight = mvPlotStyleVar.DIGITAL_BIT_HEIGHT
mvPlotStyleVar_ErrorBarSize = mvPlotStyleVar.ERROR_BAR_SIZE
mvPlotStyleVar_ErrorBarWeight = mvPlotStyleVar.ERROR_BAR_WEIGHT
mvPlotStyleVar_FillAlpha = mvPlotStyleVar.FILL_ALPHA
mvPlotStyleVar_FitPadding = mvPlotStyleVar.FIT_PADDING
mvPlotStyleVar_LabelPadding = mvPlotStyleVar.LABEL_PADDING
mvPlotStyleVar_LegendInnerPadding = mvPlotStyleVar.LEGEND_INNER_PADDING
mvPlotStyleVar_LegendPadding = mvPlotStyleVar.LEGEND_PADDING
mvPlotStyleVar_LegendSpacing = mvPlotStyleVar.LEGEND_SPACING
mvPlotStyleVar_LineWeight = mvPlotStyleVar.LINE_WEIGHT
mvPlotStyleVar_MajorGridSize = mvPlotStyleVar.MAJOR_GRID_SIZE
mvPlotStyleVar_MajorTickLen = mvPlotStyleVar.MAJOR_TICK_LEN
mvPlotStyleVar_MajorTickSize = mvPlotStyleVar.MAJOR_TICK_SIZE
mvPlotStyleVar_Marker = mvPlotStyleVar.MARKER
mvPlotStyleVar_MarkerSize = mvPlotStyleVar.MARKER_SIZE
mvPlotStyleVar_MarkerWeight = mvPlotStyleVar.MARKER_WEIGHT
mvPlotStyleVar_MinorAlpha = mvPlotStyleVar.MINOR_ALPHA
mvPlotStyleVar_MinorGridSize = mvPlotStyleVar.MINOR_GRID_SIZE
mvPlotStyleVar_MinorTickLen = mvPlotStyleVar.MINOR_TICK_LEN
mvPlotStyleVar_MinorTickSize = mvPlotStyleVar.MINOR_TICK_SIZE
mvPlotStyleVar_MousePosPadding = mvPlotStyleVar.MOUSE_POS_PADDING
mvPlotStyleVar_PlotBorderSize = mvPlotStyleVar.PLOT_BORDER_SIZE
mvPlotStyleVar_PlotDefaultSize = mvPlotStyleVar.PLOT_DEFAULT_SIZE
mvPlotStyleVar_PlotMinSize = mvPlotStyleVar.PLOT_MIN_SIZE
mvPlotStyleVar_PlotPadding = mvPlotStyleVar.PLOT_PADDING


class mvPlot(_enum.IntEnum):
    LOCATION_CENTER = _dearpygui.mvPlot_Location_Center
    LOCATION_EAST = _dearpygui.mvPlot_Location_East
    LOCATION_NORTH = _dearpygui.mvPlot_Location_North
    LOCATION_NORTH_EAST = _dearpygui.mvPlot_Location_NorthEast
    LOCATION_NORTH_WEST = _dearpygui.mvPlot_Location_NorthWest
    LOCATION_SOUTH = _dearpygui.mvPlot_Location_South
    LOCATION_SOUTH_EAST = _dearpygui.mvPlot_Location_SouthEast
    LOCATION_SOUTH_WEST = _dearpygui.mvPlot_Location_SouthWest
    LOCATION_WEST = _dearpygui.mvPlot_Location_West

mvPlot_Location_Center = mvPlot.LOCATION_CENTER
mvPlot_Location_East = mvPlot.LOCATION_EAST
mvPlot_Location_North = mvPlot.LOCATION_NORTH
mvPlot_Location_NorthEast = mvPlot.LOCATION_NORTH_EAST
mvPlot_Location_NorthWest = mvPlot.LOCATION_NORTH_WEST
mvPlot_Location_South = mvPlot.LOCATION_SOUTH
mvPlot_Location_SouthEast = mvPlot.LOCATION_SOUTH_EAST
mvPlot_Location_SouthWest = mvPlot.LOCATION_SOUTH_WEST
mvPlot_Location_West = mvPlot.LOCATION_WEST


class mvScrollDirection(_enum.IntEnum):
    HORIZONTAL = _dearpygui.mvScrollDirection_Horizontal
    VERTICAL = _dearpygui.mvScrollDirection_Vertical
    X_AXIS = _dearpygui.mvScrollDirection_XAxis
    Y_AXIS = _dearpygui.mvScrollDirection_YAxis

mvScrollDirection_Horizontal = mvScrollDirection.HORIZONTAL
mvScrollDirection_Vertical = mvScrollDirection.VERTICAL
mvScrollDirection_XAxis = mvScrollDirection.X_AXIS
mvScrollDirection_YAxis = mvScrollDirection.Y_AXIS


class mvSetScrollFlags(_enum.IntEnum):
    BOTH = _dearpygui.mvSetScrollFlags_Both
    DELAYED = _dearpygui.mvSetScrollFlags_Delayed
    NOW = _dearpygui.mvSetScrollFlags_Now

mvSetScrollFlags_Both = mvSetScrollFlags.BOTH
mvSetScrollFlags_Delayed = mvSetScrollFlags.DELAYED
mvSetScrollFlags_Now = mvSetScrollFlags.NOW


class mvStyleVar(_enum.IntEnum):
    ALPHA = _dearpygui.mvStyleVar_Alpha
    BUTTON_TEXT_ALIGN = _dearpygui.mvStyleVar_ButtonTextAlign
    CELL_PADDING = _dearpygui.mvStyleVar_CellPadding
    CHILD_BORDER_SIZE = _dearpygui.mvStyleVar_ChildBorderSize
    CHILD_ROUNDING = _dearpygui.mvStyleVar_ChildRounding
    DISABLED_ALPHA = _dearpygui.mvStyleVar_DisabledAlpha
    DOCKING_SEPARATOR_SIZE = _dearpygui.mvStyleVar_DockingSeparatorSize
    FRAME_BORDER_SIZE = _dearpygui.mvStyleVar_FrameBorderSize
    FRAME_PADDING = _dearpygui.mvStyleVar_FramePadding
    FRAME_ROUNDING = _dearpygui.mvStyleVar_FrameRounding
    GRAB_MIN_SIZE = _dearpygui.mvStyleVar_GrabMinSize
    GRAB_ROUNDING = _dearpygui.mvStyleVar_GrabRounding
    INDENT_SPACING = _dearpygui.mvStyleVar_IndentSpacing
    ITEM_INNER_SPACING = _dearpygui.mvStyleVar_ItemInnerSpacing
    ITEM_SPACING = _dearpygui.mvStyleVar_ItemSpacing
    POPUP_BORDER_SIZE = _dearpygui.mvStyleVar_PopupBorderSize
    POPUP_ROUNDING = _dearpygui.mvStyleVar_PopupRounding
    SCROLLBAR_ROUNDING = _dearpygui.mvStyleVar_ScrollbarRounding
    SCROLLBAR_SIZE = _dearpygui.mvStyleVar_ScrollbarSize
    SELECTABLE_TEXT_ALIGN = _dearpygui.mvStyleVar_SelectableTextAlign
    SEPARATOR_TEXT_ALIGN = _dearpygui.mvStyleVar_SeparatorTextAlign
    SEPARATOR_TEXT_BORDER_SIZE = _dearpygui.mvStyleVar_SeparatorTextBorderSize
    SEPARATOR_TEXT_PADDING = _dearpygui.mvStyleVar_SeparatorTextPadding
    TAB_BAR_BORDER_SIZE = _dearpygui.mvStyleVar_TabBarBorderSize
    TAB_BORDER_SIZE = _dearpygui.mvStyleVar_TabBorderSize
    TAB_ROUNDING = _dearpygui.mvStyleVar_TabRounding
    TABLE_ANGLED_HEADERS_ANGLE = _dearpygui.mvStyleVar_TableAngledHeadersAngle
    TABLE_ANGLED_HEADERS_TEXT_ALIGN = _dearpygui.mvStyleVar_TableAngledHeadersTextAlign
    WINDOW_BORDER_SIZE = _dearpygui.mvStyleVar_WindowBorderSize
    WINDOW_MIN_SIZE = _dearpygui.mvStyleVar_WindowMinSize
    WINDOW_PADDING = _dearpygui.mvStyleVar_WindowPadding
    WINDOW_ROUNDING = _dearpygui.mvStyleVar_WindowRounding
    WINDOW_TITLE_ALIGN = _dearpygui.mvStyleVar_WindowTitleAlign

mvStyleVar_Alpha = mvStyleVar.ALPHA
mvStyleVar_ButtonTextAlign = mvStyleVar.BUTTON_TEXT_ALIGN
mvStyleVar_CellPadding = mvStyleVar.CELL_PADDING
mvStyleVar_ChildBorderSize = mvStyleVar.CHILD_BORDER_SIZE
mvStyleVar_ChildRounding = mvStyleVar.CHILD_ROUNDING
mvStyleVar_DisabledAlpha = mvStyleVar.DISABLED_ALPHA
mvStyleVar_DockingSeparatorSize = mvStyleVar.DOCKING_SEPARATOR_SIZE
mvStyleVar_FrameBorderSize = mvStyleVar.FRAME_BORDER_SIZE
mvStyleVar_FramePadding = mvStyleVar.FRAME_PADDING
mvStyleVar_FrameRounding = mvStyleVar.FRAME_ROUNDING
mvStyleVar_GrabMinSize = mvStyleVar.GRAB_MIN_SIZE
mvStyleVar_GrabRounding = mvStyleVar.GRAB_ROUNDING
mvStyleVar_IndentSpacing = mvStyleVar.INDENT_SPACING
mvStyleVar_ItemInnerSpacing = mvStyleVar.ITEM_INNER_SPACING
mvStyleVar_ItemSpacing = mvStyleVar.ITEM_SPACING
mvStyleVar_PopupBorderSize = mvStyleVar.POPUP_BORDER_SIZE
mvStyleVar_PopupRounding = mvStyleVar.POPUP_ROUNDING
mvStyleVar_ScrollbarRounding = mvStyleVar.SCROLLBAR_ROUNDING
mvStyleVar_ScrollbarSize = mvStyleVar.SCROLLBAR_SIZE
mvStyleVar_SelectableTextAlign = mvStyleVar.SELECTABLE_TEXT_ALIGN
mvStyleVar_SeparatorTextAlign = mvStyleVar.SEPARATOR_TEXT_ALIGN
mvStyleVar_SeparatorTextBorderSize = mvStyleVar.SEPARATOR_TEXT_BORDER_SIZE
mvStyleVar_SeparatorTextPadding = mvStyleVar.SEPARATOR_TEXT_PADDING
mvStyleVar_TabBarBorderSize = mvStyleVar.TAB_BAR_BORDER_SIZE
mvStyleVar_TabBorderSize = mvStyleVar.TAB_BORDER_SIZE
mvStyleVar_TabRounding = mvStyleVar.TAB_ROUNDING
mvStyleVar_TableAngledHeadersAngle = mvStyleVar.TABLE_ANGLED_HEADERS_ANGLE
mvStyleVar_TableAngledHeadersTextAlign = mvStyleVar.TABLE_ANGLED_HEADERS_TEXT_ALIGN
mvStyleVar_WindowBorderSize = mvStyleVar.WINDOW_BORDER_SIZE
mvStyleVar_WindowMinSize = mvStyleVar.WINDOW_MIN_SIZE
mvStyleVar_WindowPadding = mvStyleVar.WINDOW_PADDING
mvStyleVar_WindowRounding = mvStyleVar.WINDOW_ROUNDING
mvStyleVar_WindowTitleAlign = mvStyleVar.WINDOW_TITLE_ALIGN


class mvTabOrder(_enum.IntEnum):
    FIXED = _dearpygui.mvTabOrder_Fixed
    LEADING = _dearpygui.mvTabOrder_Leading
    REORDERABLE = _dearpygui.mvTabOrder_Reorderable
    TRAILING = _dearpygui.mvTabOrder_Trailing

mvTabOrder_Fixed = mvTabOrder.FIXED
mvTabOrder_Leading = mvTabOrder.LEADING
mvTabOrder_Reorderable = mvTabOrder.REORDERABLE
mvTabOrder_Trailing = mvTabOrder.TRAILING


class mvThemeCat(_enum.IntEnum):
    CORE = _dearpygui.mvThemeCat_Core
    NODES = _dearpygui.mvThemeCat_Nodes
    PLOTS = _dearpygui.mvThemeCat_Plots

mvThemeCat_Core = mvThemeCat.CORE
mvThemeCat_Nodes = mvThemeCat.NODES
mvThemeCat_Plots = mvThemeCat.PLOTS


class mvThemeCol(_enum.IntEnum):
    BORDER = _dearpygui.mvThemeCol_Border
    BORDER_SHADOW = _dearpygui.mvThemeCol_BorderShadow
    BUTTON = _dearpygui.mvThemeCol_Button
    BUTTON_ACTIVE = _dearpygui.mvThemeCol_ButtonActive
    BUTTON_HOVERED = _dearpygui.mvThemeCol_ButtonHovered
    CHECK_MARK = _dearpygui.mvThemeCol_CheckMark
    CHILD_BG = _dearpygui.mvThemeCol_ChildBg
    DOCKING_EMPTY_BG = _dearpygui.mvThemeCol_DockingEmptyBg
    DOCKING_PREVIEW = _dearpygui.mvThemeCol_DockingPreview
    DRAG_DROP_TARGET = _dearpygui.mvThemeCol_DragDropTarget
    FRAME_BG = _dearpygui.mvThemeCol_FrameBg
    FRAME_BG_ACTIVE = _dearpygui.mvThemeCol_FrameBgActive
    FRAME_BG_HOVERED = _dearpygui.mvThemeCol_FrameBgHovered
    HEADER = _dearpygui.mvThemeCol_Header
    HEADER_ACTIVE = _dearpygui.mvThemeCol_HeaderActive
    HEADER_HOVERED = _dearpygui.mvThemeCol_HeaderHovered
    MENU_BAR_BG = _dearpygui.mvThemeCol_MenuBarBg
    MODAL_WINDOW_DIM_BG = _dearpygui.mvThemeCol_ModalWindowDimBg
    NAV_HIGHLIGHT = _dearpygui.mvThemeCol_NavHighlight
    NAV_WINDOWING_DIM_BG = _dearpygui.mvThemeCol_NavWindowingDimBg
    NAV_WINDOWING_HIGHLIGHT = _dearpygui.mvThemeCol_NavWindowingHighlight
    PLOT_HISTOGRAM = _dearpygui.mvThemeCol_PlotHistogram
    PLOT_HISTOGRAM_HOVERED = _dearpygui.mvThemeCol_PlotHistogramHovered
    PLOT_LINES = _dearpygui.mvThemeCol_PlotLines
    PLOT_LINES_HOVERED = _dearpygui.mvThemeCol_PlotLinesHovered
    POPUP_BG = _dearpygui.mvThemeCol_PopupBg
    RESIZE_GRIP = _dearpygui.mvThemeCol_ResizeGrip
    RESIZE_GRIP_ACTIVE = _dearpygui.mvThemeCol_ResizeGripActive
    RESIZE_GRIP_HOVERED = _dearpygui.mvThemeCol_ResizeGripHovered
    SCROLLBAR_BG = _dearpygui.mvThemeCol_ScrollbarBg
    SCROLLBAR_GRAB = _dearpygui.mvThemeCol_ScrollbarGrab
    SCROLLBAR_GRAB_ACTIVE = _dearpygui.mvThemeCol_ScrollbarGrabActive
    SCROLLBAR_GRAB_HOVERED = _dearpygui.mvThemeCol_ScrollbarGrabHovered
    SEPARATOR = _dearpygui.mvThemeCol_Separator
    SEPARATOR_ACTIVE = _dearpygui.mvThemeCol_SeparatorActive
    SEPARATOR_HOVERED = _dearpygui.mvThemeCol_SeparatorHovered
    SLIDER_GRAB = _dearpygui.mvThemeCol_SliderGrab
    SLIDER_GRAB_ACTIVE = _dearpygui.mvThemeCol_SliderGrabActive
    TAB = _dearpygui.mvThemeCol_Tab
    TAB_ACTIVE = _dearpygui.mvThemeCol_TabActive
    TAB_HOVERED = _dearpygui.mvThemeCol_TabHovered
    TAB_UNFOCUSED = _dearpygui.mvThemeCol_TabUnfocused
    TAB_UNFOCUSED_ACTIVE = _dearpygui.mvThemeCol_TabUnfocusedActive
    TABLE_BORDER_LIGHT = _dearpygui.mvThemeCol_TableBorderLight
    TABLE_BORDER_STRONG = _dearpygui.mvThemeCol_TableBorderStrong
    TABLE_HEADER_BG = _dearpygui.mvThemeCol_TableHeaderBg
    TABLE_ROW_BG = _dearpygui.mvThemeCol_TableRowBg
    TABLE_ROW_BG_ALT = _dearpygui.mvThemeCol_TableRowBgAlt
    TEXT = _dearpygui.mvThemeCol_Text
    TEXT_DISABLED = _dearpygui.mvThemeCol_TextDisabled
    TEXT_SELECTED_BG = _dearpygui.mvThemeCol_TextSelectedBg
    TITLE_BG = _dearpygui.mvThemeCol_TitleBg
    TITLE_BG_ACTIVE = _dearpygui.mvThemeCol_TitleBgActive
    TITLE_BG_COLLAPSED = _dearpygui.mvThemeCol_TitleBgCollapsed
    WINDOW_BG = _dearpygui.mvThemeCol_WindowBg

mvThemeCol_Border = mvThemeCol.BORDER
mvThemeCol_BorderShadow = mvThemeCol.BORDER_SHADOW
mvThemeCol_Button = mvThemeCol.BUTTON
mvThemeCol_ButtonActive = mvThemeCol.BUTTON_ACTIVE
mvThemeCol_ButtonHovered = mvThemeCol.BUTTON_HOVERED
mvThemeCol_CheckMark = mvThemeCol.CHECK_MARK
mvThemeCol_ChildBg = mvThemeCol.CHILD_BG
mvThemeCol_DockingEmptyBg = mvThemeCol.DOCKING_EMPTY_BG
mvThemeCol_DockingPreview = mvThemeCol.DOCKING_PREVIEW
mvThemeCol_DragDropTarget = mvThemeCol.DRAG_DROP_TARGET
mvThemeCol_FrameBg = mvThemeCol.FRAME_BG
mvThemeCol_FrameBgActive = mvThemeCol.FRAME_BG_ACTIVE
mvThemeCol_FrameBgHovered = mvThemeCol.FRAME_BG_HOVERED
mvThemeCol_Header = mvThemeCol.HEADER
mvThemeCol_HeaderActive = mvThemeCol.HEADER_ACTIVE
mvThemeCol_HeaderHovered = mvThemeCol.HEADER_HOVERED
mvThemeCol_MenuBarBg = mvThemeCol.MENU_BAR_BG
mvThemeCol_ModalWindowDimBg = mvThemeCol.MODAL_WINDOW_DIM_BG
mvThemeCol_NavHighlight = mvThemeCol.NAV_HIGHLIGHT
mvThemeCol_NavWindowingDimBg = mvThemeCol.NAV_WINDOWING_DIM_BG
mvThemeCol_NavWindowingHighlight = mvThemeCol.NAV_WINDOWING_HIGHLIGHT
mvThemeCol_PlotHistogram = mvThemeCol.PLOT_HISTOGRAM
mvThemeCol_PlotHistogramHovered = mvThemeCol.PLOT_HISTOGRAM_HOVERED
mvThemeCol_PlotLines = mvThemeCol.PLOT_LINES
mvThemeCol_PlotLinesHovered = mvThemeCol.PLOT_LINES_HOVERED
mvThemeCol_PopupBg = mvThemeCol.POPUP_BG
mvThemeCol_ResizeGrip = mvThemeCol.RESIZE_GRIP
mvThemeCol_ResizeGripActive = mvThemeCol.RESIZE_GRIP_ACTIVE
mvThemeCol_ResizeGripHovered = mvThemeCol.RESIZE_GRIP_HOVERED
mvThemeCol_ScrollbarBg = mvThemeCol.SCROLLBAR_BG
mvThemeCol_ScrollbarGrab = mvThemeCol.SCROLLBAR_GRAB
mvThemeCol_ScrollbarGrabActive = mvThemeCol.SCROLLBAR_GRAB_ACTIVE
mvThemeCol_ScrollbarGrabHovered = mvThemeCol.SCROLLBAR_GRAB_HOVERED
mvThemeCol_Separator = mvThemeCol.SEPARATOR
mvThemeCol_SeparatorActive = mvThemeCol.SEPARATOR_ACTIVE
mvThemeCol_SeparatorHovered = mvThemeCol.SEPARATOR_HOVERED
mvThemeCol_SliderGrab = mvThemeCol.SLIDER_GRAB
mvThemeCol_SliderGrabActive = mvThemeCol.SLIDER_GRAB_ACTIVE
mvThemeCol_Tab = mvThemeCol.TAB
mvThemeCol_TabActive = mvThemeCol.TAB_ACTIVE
mvThemeCol_TabHovered = mvThemeCol.TAB_HOVERED
mvThemeCol_TabUnfocused = mvThemeCol.TAB_UNFOCUSED
mvThemeCol_TabUnfocusedActive = mvThemeCol.TAB_UNFOCUSED_ACTIVE
mvThemeCol_TableBorderLight = mvThemeCol.TABLE_BORDER_LIGHT
mvThemeCol_TableBorderStrong = mvThemeCol.TABLE_BORDER_STRONG
mvThemeCol_TableHeaderBg = mvThemeCol.TABLE_HEADER_BG
mvThemeCol_TableRowBg = mvThemeCol.TABLE_ROW_BG
mvThemeCol_TableRowBgAlt = mvThemeCol.TABLE_ROW_BG_ALT
mvThemeCol_Text = mvThemeCol.TEXT
mvThemeCol_TextDisabled = mvThemeCol.TEXT_DISABLED
mvThemeCol_TextSelectedBg = mvThemeCol.TEXT_SELECTED_BG
mvThemeCol_TitleBg = mvThemeCol.TITLE_BG
mvThemeCol_TitleBgActive = mvThemeCol.TITLE_BG_ACTIVE
mvThemeCol_TitleBgCollapsed = mvThemeCol.TITLE_BG_COLLAPSED
mvThemeCol_WindowBg = mvThemeCol.WINDOW_BG


class mvTimeUnit(_enum.IntEnum):
    DAY = _dearpygui.mvTimeUnit_Day
    HR = _dearpygui.mvTimeUnit_Hr
    MIN = _dearpygui.mvTimeUnit_Min
    MO = _dearpygui.mvTimeUnit_Mo
    MS = _dearpygui.mvTimeUnit_Ms
    S = _dearpygui.mvTimeUnit_S
    US = _dearpygui.mvTimeUnit_Us
    YR = _dearpygui.mvTimeUnit_Yr

mvTimeUnit_Day = mvTimeUnit.DAY
mvTimeUnit_Hr = mvTimeUnit.HR
mvTimeUnit_Min = mvTimeUnit.MIN
mvTimeUnit_Mo = mvTimeUnit.MO
mvTimeUnit_Ms = mvTimeUnit.MS
mvTimeUnit_S = mvTimeUnit.S
mvTimeUnit_Us = mvTimeUnit.US
mvTimeUnit_Yr = mvTimeUnit.YR


class mvTool(_enum.IntEnum):
    ABOUT = _dearpygui.mvTool_About
    DEBUG = _dearpygui.mvTool_Debug
    DOC = _dearpygui.mvTool_Doc
    FONT = _dearpygui.mvTool_Font
    ITEM_REGISTRY = _dearpygui.mvTool_ItemRegistry
    METRICS = _dearpygui.mvTool_Metrics
    STACK = _dearpygui.mvTool_Stack
    STYLE = _dearpygui.mvTool_Style

mvTool_About = mvTool.ABOUT
mvTool_Debug = mvTool.DEBUG
mvTool_Doc = mvTool.DOC
mvTool_Font = mvTool.FONT
mvTool_ItemRegistry = mvTool.ITEM_REGISTRY
mvTool_Metrics = mvTool.METRICS
mvTool_Stack = mvTool.STACK
mvTool_Style = mvTool.STYLE



class mvNodePinShape(_enum.IntEnum):
    CIRCLE = _dearpygui.mvNode_PinShape_Circle
    CIRCLE_FILLED = _dearpygui.mvNode_PinShape_CircleFilled
    QUAD = _dearpygui.mvNode_PinShape_Quad
    QUAD_FILLED = _dearpygui.mvNode_PinShape_QuadFilled
    TRIANGLE = _dearpygui.mvNode_PinShape_Triangle
    TRIANGLE_FILLED = _dearpygui.mvNode_PinShape_TriangleFilled

mvNode_PinShape_Circle = mvNodePinShape.CIRCLE
mvNode_PinShape_CircleFilled = mvNodePinShape.CIRCLE_FILLED
mvNode_PinShape_Quad = mvNodePinShape.QUAD
mvNode_PinShape_QuadFilled = mvNodePinShape.QUAD_FILLED
mvNode_PinShape_Triangle = mvNodePinShape.TRIANGLE
mvNode_PinShape_TriangleFilled = mvNodePinShape.TRIANGLE_FILLED


class mvNodeAttr(_enum.IntEnum):
    INPUT = _dearpygui.mvNode_Attr_Input
    OUTPUT = _dearpygui.mvNode_Attr_Output
    STATIC = _dearpygui.mvNode_Attr_Static

mvNode_Attr_Input = mvNodeAttr.INPUT
mvNode_Attr_Output = mvNodeAttr.OUTPUT
mvNode_Attr_Static = mvNodeAttr.STATIC


class mvTableSizing(_enum.IntEnum):
    FIXED_FIT = _dearpygui.mvTable_SizingFixedFit
    FIXED_SAME = _dearpygui.mvTable_SizingFixedSame
    STRETCH_PROP = _dearpygui.mvTable_SizingStretchProp
    STRETCH_SAME = _dearpygui.mvTable_SizingStretchSame

mvTable_SizingFixedFit = mvTableSizing.FIXED_FIT
mvTable_SizingFixedSame = mvTableSizing.FIXED_SAME
mvTable_SizingStretchProp = mvTableSizing.STRETCH_PROP
mvTable_SizingStretchSame = mvTableSizing.STRETCH_SAME


class _CodeMapEnumType(_enum.EnumMeta):

    def __getitem__(self, name: str):
        key = name.upper().replace(' ', '_').replace('-', '_')
        try:
            return self._member_map_[key]

        except KeyError:
            raise KeyError(name) from None


class KeyCode(_enum.IntEnum, metaclass=_CodeMapEnumType):

    """Contains all possible values for handler and input key arguments."""
    MOD_DISABLED = _dearpygui.mvKey_ModDisabled
    NONE = ANY = _dearpygui.mvKey_None
    CLEAR = _dearpygui.mvKey_Clear
    PRIOR = _dearpygui.mvKey_Prior
    NEXT = _dearpygui.mvKey_Next
    SELECT = SEL = _dearpygui.mvKey_Select
    EXECUTE = EXEC = _dearpygui.mvKey_Execute
    HELP = _dearpygui.mvKey_Help
    L_WIN = _dearpygui.mvKey_LWin
    R_WIN = _dearpygui.mvKey_RWin
    APPS = _dearpygui.mvKey_Apps
    SLEEP = _dearpygui.mvKey_Sleep
    F25 = _dearpygui.mvKey_F25
    BROWSER_REFRESH = _dearpygui.mvKey_Browser_Refresh
    BROWSER_STOP = _dearpygui.mvKey_Browser_Stop
    BROWSER_SEARCH = _dearpygui.mvKey_Browser_Search
    BROWSER_FAVORITES = _dearpygui.mvKey_Browser_Favorites
    BROWSER_HOME = _dearpygui.mvKey_Browser_Home
    VOLUME_MUTE = VOL_MUTE = _dearpygui.mvKey_Volume_Mute
    VOLUME_DOWN = VOL_DOWN = VOL_DN = _dearpygui.mvKey_Volume_Down
    VOLUME_UP = VOL_UP = _dearpygui.mvKey_Volume_Up
    MEDIA_NEXT_TRACK = NEXT_TRACK = _dearpygui.mvKey_Media_Next_Track
    MEDIA_PREV_TRACK = PREV_TRACK = _dearpygui.mvKey_Media_Prev_Track
    MEDIA_STOP = STOP_TRACK = _dearpygui.mvKey_Media_Stop
    MEDIA_PLAY_PAUSE = PLAY_TRACK = PAUSE_TRACK = _dearpygui.mvKey_Media_Play_Pause
    LAUNCH_MAIL = _dearpygui.mvKey_Launch_Mail
    LAUNCH_MEDIA_SELECT = _dearpygui.mvKey_Launch_Media_Select
    LAUNCH_APP_1 = _dearpygui.mvKey_Launch_App1
    LAUNCH_APP_2 = _dearpygui.mvKey_Launch_App2
    COLON = _dearpygui.mvKey_Colon
    PLUS = _dearpygui.mvKey_Plus
    TILDE = _dearpygui.mvKey_Tilde
    QUOTE = _dearpygui.mvKey_Quote
    TAB = _dearpygui.mvKey_Tab
    LEFT = LEFT_ARROW = _dearpygui.mvKey_Left
    RIGHT = RIGHT_ARROW = _dearpygui.mvKey_Right
    UP = UP_ARROW = _dearpygui.mvKey_Up
    DOWN = DOWN_ARROW = _dearpygui.mvKey_Down
    PAGE_UP = PG_UP = PGUP = 517
    PAGE_DOWN = PG_DN = PGDN = 518
    HOME = _dearpygui.mvKey_Home
    END = _dearpygui.mvKey_End
    INSERT = INS = _dearpygui.mvKey_Insert
    DELETE = DEL = _dearpygui.mvKey_Delete
    BACK = BACKSPACE = _dearpygui.mvKey_Back
    SPACEBAR = SPACE = _dearpygui.mvKey_Spacebar
    RETURN = ENTER = _dearpygui.mvKey_Return
    ESCAPE = ESC = _dearpygui.mvKey_Escape
    L_CONTROL = L_CTRL = LCONTROL = LCTRL = _dearpygui.mvKey_LControl
    L_SHIFT = LSHIFT = _dearpygui.mvKey_LShift
    L_ALT = LALT = _dearpygui.mvKey_LAlt
    L_SUPER = LSUPER = 530
    R_CONTROL = RCONTROL = R_CTRL = RCTRL = _dearpygui.mvKey_RControl
    R_SHIFT = RSHIFT = _dearpygui.mvKey_RShift
    R_ALT = RALT = _dearpygui.mvKey_RAlt
    R_SUPER = RSUPER = 534
    MENU = _dearpygui.mvKey_Menu
    DIGIT_0 = _dearpygui.mvKey_0
    DIGIT_1 = _dearpygui.mvKey_1
    DIGIT_2 = _dearpygui.mvKey_2
    DIGIT_3 = _dearpygui.mvKey_3
    DIGIT_4 = _dearpygui.mvKey_4
    DIGIT_5 = _dearpygui.mvKey_5
    DIGIT_6 = _dearpygui.mvKey_6
    DIGIT_7 = _dearpygui.mvKey_7
    DIGIT_8 = _dearpygui.mvKey_8
    DIGIT_9 = _dearpygui.mvKey_9
    A = _dearpygui.mvKey_A
    B = _dearpygui.mvKey_B
    C = _dearpygui.mvKey_C
    D = _dearpygui.mvKey_D
    E = _dearpygui.mvKey_E
    F = _dearpygui.mvKey_F
    G = _dearpygui.mvKey_G
    H = _dearpygui.mvKey_H
    I = _dearpygui.mvKey_I
    J = _dearpygui.mvKey_J
    K = _dearpygui.mvKey_K
    L = _dearpygui.mvKey_L
    M = _dearpygui.mvKey_M
    N = _dearpygui.mvKey_N
    O = _dearpygui.mvKey_O
    P = _dearpygui.mvKey_P
    Q = _dearpygui.mvKey_Q
    R = _dearpygui.mvKey_R
    S = _dearpygui.mvKey_S
    T = _dearpygui.mvKey_T
    U = _dearpygui.mvKey_U
    V = _dearpygui.mvKey_V
    W = _dearpygui.mvKey_W
    X = _dearpygui.mvKey_X
    Y = _dearpygui.mvKey_Y
    Z = _dearpygui.mvKey_Z
    F1 = _dearpygui.mvKey_F1
    F2 = _dearpygui.mvKey_F2
    F3 = _dearpygui.mvKey_F3
    F4 = _dearpygui.mvKey_F4
    F5 = _dearpygui.mvKey_F5
    F6 = _dearpygui.mvKey_F6
    F7 = _dearpygui.mvKey_F7
    F8 = _dearpygui.mvKey_F8
    F9 = _dearpygui.mvKey_F9
    F10 = _dearpygui.mvKey_F10
    F11 = _dearpygui.mvKey_F11
    F12 = _dearpygui.mvKey_F12
    F13 = _dearpygui.mvKey_F13
    F14 = _dearpygui.mvKey_F14
    F15 = _dearpygui.mvKey_F15
    F16 = _dearpygui.mvKey_F16
    F17 = _dearpygui.mvKey_F17
    F18 = _dearpygui.mvKey_F18
    F19 = _dearpygui.mvKey_F19
    F20 = _dearpygui.mvKey_F20
    F21 = _dearpygui.mvKey_F21
    F22 = _dearpygui.mvKey_F22
    F23 = _dearpygui.mvKey_F23
    F24 = _dearpygui.mvKey_F24
    APOSTROPHE = 596
    COMMA = _dearpygui.mvKey_Comma
    MINUS = _dearpygui.mvKey_Minus
    PERIOD = _dearpygui.mvKey_Period
    SLASH = FORWARD_SLASH = _dearpygui.mvKey_Slash
    SEMICOLON = 601
    EQUAL = 602
    OPEN_BRACE = _dearpygui.mvKey_Open_Brace
    BACKSLASH = BACK_SLASH = _dearpygui.mvKey_Backslash
    CLOSE_BRACE = _dearpygui.mvKey_Close_Brace
    GRAVE_ACCENT = ACCENT = 606
    CAPS_LOCK = CAPS = CAPS_LCK = CAPSLCK = _dearpygui.mvKey_CapsLock
    SCROLL_LOCK = SCRLCK = SCR_LCK = _dearpygui.mvKey_ScrollLock
    NUM_LOCK = NUMLCK = NUM_LCK = _dearpygui.mvKey_NumLock
    PRINT = PRINT_SCREEN = PRT_SCR = PRTSCR = _dearpygui.mvKey_Print
    PAUSE = _dearpygui.mvKey_Pause
    NUMPAD_0 = NUM_0 = _dearpygui.mvKey_NumPad0
    NUMPAD_1 = NUM_1 = _dearpygui.mvKey_NumPad1
    NUMPAD_2 = NUM_2 = _dearpygui.mvKey_NumPad2
    NUMPAD_3 = NUM_3 = _dearpygui.mvKey_NumPad3
    NUMPAD_4 = NUM_4 = _dearpygui.mvKey_NumPad4
    NUMPAD_5 = NUM_5 = _dearpygui.mvKey_NumPad5
    NUMPAD_6 = NUM_6 = _dearpygui.mvKey_NumPad6
    NUMPAD_7 = NUM_7 = _dearpygui.mvKey_NumPad7
    NUMPAD_8 = NUM_8 = _dearpygui.mvKey_NumPad8
    NUMPAD_9 = NUM_9 = _dearpygui.mvKey_NumPad9
    DECIMAL = NUMPAD_DECIMAL = NUM_DECIMAL = _dearpygui.mvKey_Decimal
    DIVIDE = NUMPAD_DIVIDE = NUM_DIVIDE = _dearpygui.mvKey_Divide
    MULTIPLY = NUMPAD_MULTIPLY = NUM_MULTIPLY = _dearpygui.mvKey_Multiply
    SUBTRACT = NUMPAD_SUBTRACT = NUM_SUBTRACT = _dearpygui.mvKey_Subtract
    ADD = NUMPAD_ADD = NUM_ADD = _dearpygui.mvKey_Add
    NUMPAD_ENTER = NUM_ENTER = _dearpygui.mvKey_NumPadEnter
    NUMPAD_EQUAL = NUM_EQUAL = _dearpygui.mvKey_NumPadEqual
    BROWSER_BACK = _dearpygui.mvKey_Browser_Back
    BROWSER_FORWARD = _dearpygui.mvKey_Browser_Forward
    GAMEPAD_START = 631
    GAMEPAD_BACK = 632
    GAMEPAD_FACE_LEFT = 633
    GAMEPAD_FACE_RIGHT = 634
    GAMEPAD_FACE_UP = 635
    GAMEPAD_FACE_DOWN = 636
    GAMEPAD_DPAD_LEFT = 637
    GAMEPAD_DPAD_RIGHT = 638
    GAMEPAD_DPAD_UP = 639
    GAMEPAD_DPAD_DOWN = 640
    GAMEPAD_L1 = 641
    GAMEPAD_R1 = 642
    GAMEPAD_L2 = 643
    GAMEPAD_R2 = 644
    GAMEPAD_L3 = 645
    GAMEPAD_R3 = 646
    GAMEPAD_LSTICK_LEFT = 647
    GAMEPAD_LSTICK_RIGHT = 648
    GAMEPAD_LSTICK_UP = 649
    GAMEPAD_LSTICK_DOWN = 650
    GAMEPAD_RSTICK_LEFT = 651
    GAMEPAD_RSTICK_RIGHT = 652
    GAMEPAD_RSTICK_UP = 653
    GAMEPAD_RSTICK_DOWN = 654
    MOUSE_LEFT = LEFT_CLICK = LMB = 655
    MOUSE_RIGHT = RIGHT_CLICK = RMB = 656
    MOUSE_MIDDLE = MIDDLE_CLICK = MMB = 657
    MOUSE_X1 = 658
    MOUSE_X2 = 659
    MOUSE_WHEEL_X = SCROLL_H = H_SCROLL = 660
    MOUSE_WHEEL_Y = SCROLL_V = V_SCROLL = 661
    MOD_CTRL = _dearpygui.mvKey_ModCtrl
    MOD_SHIFT = _dearpygui.mvKey_ModShift
    MOD_ALT = _dearpygui.mvKey_ModAlt
    MOD_SUPER = _dearpygui.mvKey_ModSuper

mvKey = KeyCode
mvKey.EQUAL._add_alias_('=')
mvKey.SEMICOLON._add_alias_(';')
mvKey.GRAVE_ACCENT._add_alias_('`')
mvKey.APOSTROPHE._add_alias_("'")
mvKey_ModDisabled = mvKey.MOD_DISABLED
mvKey_None = mvKey.NONE
mvKey_None._add_alias_('')
mvKey_None._add_value_alias_(None)
mvKey_Clear = mvKey.CLEAR
mvKey_Prior = mvKey.PRIOR
mvKey_Next = mvKey.NEXT
mvKey_Select = mvKey.SELECT
mvKey_Execute = mvKey.EXECUTE
mvKey_Help = mvKey.HELP
mvKey_LWin = mvKey.L_WIN
mvKey_RWin = mvKey.R_WIN
mvKey_Apps = mvKey.APPS
mvKey_Sleep = mvKey.SLEEP
mvKey_F25 = mvKey.F25
mvKey_Browser_Refresh = mvKey.BROWSER_REFRESH
mvKey_Browser_Stop = mvKey.BROWSER_STOP
mvKey_Browser_Search = mvKey.BROWSER_SEARCH
mvKey_Browser_Favorites = mvKey.BROWSER_FAVORITES
mvKey_Browser_Home = mvKey.BROWSER_HOME
mvKey_Volume_Mute = mvKey.VOLUME_MUTE
mvKey_Volume_Mute._add_alias_('VOL+')
mvKey_Volume_Down = mvKey.VOLUME_DOWN
mvKey_Volume_Down._add_alias_('VOL_')
mvKey_Volume_Up = mvKey.VOLUME_UP
mvKey_Volume_Up._add_alias_('VOL/')
mvKey_Media_Next_Track = mvKey.MEDIA_NEXT_TRACK
mvKey_Media_Prev_Track = mvKey.MEDIA_PREV_TRACK
mvKey_Media_Stop = mvKey.MEDIA_STOP
mvKey_Media_Play_Pause = mvKey.MEDIA_PLAY_PAUSE
mvKey_Launch_Mail = mvKey.LAUNCH_MAIL
mvKey_Launch_Media_Select = mvKey.LAUNCH_MEDIA_SELECT
mvKey_Launch_App1 = mvKey.LAUNCH_APP_1
mvKey_Launch_App2 = mvKey.LAUNCH_APP_2
mvKey_Colon = mvKey.COLON
mvKey_Colon._add_alias_(':')
mvKey_Plus = mvKey.PLUS
mvKey_Tilde = mvKey.TILDE
mvKey_Tilde._add_alias_('~')
mvKey_Quote = mvKey.QUOTE
mvKey_Quote._add_alias_('"')
mvKey_Tab = mvKey.TAB
mvKey_Left = mvKey.LEFT
mvKey_Right = mvKey.RIGHT
mvKey_Up = mvKey.UP
mvKey_Down = mvKey.DOWN
mvKey_Home = mvKey.HOME
mvKey_End = mvKey.END
mvKey_Insert = mvKey.INSERT
mvKey_Delete = mvKey.DELETE
mvKey_Back = mvKey.BACK
mvKey_Spacebar = mvKey.SPACEBAR
mvKey_Return = mvKey.RETURN
mvKey_Escape = mvKey.ESCAPE
mvKey_LControl = mvKey.L_CONTROL
mvKey_LShift = mvKey.L_SHIFT
mvKey_LAlt = mvKey.L_ALT
vKey_RControl = mvKey.R_CONTROL
mvKey_RShift = mvKey.R_SHIFT
mvKey_RAlt = mvKey.R_ALT
mvKey_Menu = mvKey.MENU
mvKey_0 = mvKey.DIGIT_0
mvKey.DIGIT_0._add_alias_('0')
mvKey_1 = mvKey.DIGIT_1
mvKey.DIGIT_1._add_alias_('1')
mvKey_2 = mvKey.DIGIT_2
mvKey.DIGIT_2._add_alias_('2')
mvKey_3 = mvKey.DIGIT_3
mvKey.DIGIT_3._add_alias_('3')
mvKey_4 = mvKey.DIGIT_4
mvKey.DIGIT_4._add_alias_('4')
mvKey_5 = mvKey.DIGIT_5
mvKey.DIGIT_5._add_alias_('5')
mvKey_6 = mvKey.DIGIT_6
mvKey.DIGIT_6._add_alias_('6')
mvKey_7 = mvKey.DIGIT_7
mvKey.DIGIT_7._add_alias_('7')
mvKey_8 = mvKey.DIGIT_8
mvKey.DIGIT_8._add_alias_('8')
mvKey_9 = mvKey.DIGIT_9
mvKey.DIGIT_9._add_alias_('9')
mvKey_A = mvKey.A
mvKey_B = mvKey.B
mvKey_C = mvKey.C
mvKey_D = mvKey.D
mvKey_E = mvKey.E
mvKey_F = mvKey.F
mvKey_G = mvKey.G
mvKey_H = mvKey.H
mvKey_I = mvKey.I
mvKey_J = mvKey.J
mvKey_K = mvKey.K
mvKey_L = mvKey.L
mvKey_M = mvKey.M
mvKey_N = mvKey.N
mvKey_O = mvKey.O
mvKey_P = mvKey.P
mvKey_Q = mvKey.Q
mvKey_R = mvKey.R
mvKey_S = mvKey.S
mvKey_T = mvKey.T
mvKey_U = mvKey.U
mvKey_V = mvKey.V
mvKey_W = mvKey.W
mvKey_X = mvKey.X
mvKey_Y = mvKey.Y
mvKey_Z = mvKey.Z
mvKey_F1 = mvKey.F1
mvKey_F2 = mvKey.F2
mvKey_F3 = mvKey.F3
mvKey_F4 = mvKey.F4
mvKey_F5 = mvKey.F5
mvKey_F6 = mvKey.F6
mvKey_F7 = mvKey.F7
mvKey_F8 = mvKey.F8
mvKey_F9 = mvKey.F9
mvKey_F10 = mvKey.F10
mvKey_F11 = mvKey.F11
mvKey_F12 = mvKey.F12
mvKey_F13 = mvKey.F13
mvKey_F14 = mvKey.F14
mvKey_F15 = mvKey.F15
mvKey_F16 = mvKey.F16
mvKey_F17 = mvKey.F17
mvKey_F18 = mvKey.F18
mvKey_F19 = mvKey.F19
mvKey_F20 = mvKey.F20
mvKey_F21 = mvKey.F21
mvKey_F22 = mvKey.F22
mvKey_F23 = mvKey.F23
mvKey_F24 = mvKey.F24
mvKey_Comma = mvKey.COMMA
mvKey_Comma._add_alias_(',')
mvKey_Minus = mvKey.MINUS
mvKey_Period = mvKey.PERIOD
mvKey_Slash = mvKey.SLASH
mvKey_Open_Brace = mvKey.OPEN_BRACE
mvKey_Open_Brace._add_alias_('[')
mvKey_Backslash = mvKey.BACKSLASH
mvKey_Backslash._add_alias_('\\')
mvKey_Close_Brace = mvKey.CLOSE_BRACE
mvKey_Close_Brace._add_alias_(']')
mvKey_CapsLock = mvKey.CAPS_LOCK
mvKey_ScrollLock = mvKey.SCROLL_LOCK
mvKey_NumLock = mvKey.NUM_LOCK
mvKey_Print = mvKey.PRINT
mvKey_Pause = mvKey.PAUSE
mvKey_NumPad0 = mvKey.NUMPAD_0
mvKey_NumPad1 = mvKey.NUMPAD_1
mvKey_NumPad2 = mvKey.NUMPAD_2
mvKey_NumPad3 = mvKey.NUMPAD_3
mvKey_NumPad4 = mvKey.NUMPAD_4
mvKey_NumPad5 = mvKey.NUMPAD_5
mvKey_NumPad6 = mvKey.NUMPAD_6
mvKey_NumPad7 = mvKey.NUMPAD_7
mvKey_NumPad8 = mvKey.NUMPAD_8
mvKey_NumPad9 = mvKey.NUMPAD_9
mvKey_Decimal = mvKey.DECIMAL
mvKey_Decimal._add_alias_('.')
mvKey_Divide = mvKey.DIVIDE
mvKey_Divide._add_alias_('/')
mvKey_Multiply = mvKey.MULTIPLY
mvKey_Multiply._add_alias_('*')
mvKey_Subtract = mvKey.SUBTRACT
mvKey_Subtract._add_alias_('-')
mvKey_Add = mvKey.ADD
mvKey_Add._add_alias_('+')
mvKey_NumPadEnter = mvKey.NUMPAD_ENTER
mvKey_NumPadEqual = mvKey.NUMPAD_EQUAL
mvKey_Browser_Back = mvKey.BROWSER_BACK
mvKey_Browser_Forward = mvKey.BROWSER_FORWARD
mvKey_ModCtrl = mvKey.MOD_CTRL
mvKey_ModShift = mvKey.MOD_SHIFT
mvKey_ModAlt = mvKey.MOD_ALT
mvKey_ModSuper = mvKey.MOD_SUPER


class PointerCode(_enum.IntEnum, metaclass=_CodeMapEnumType):
    """Contains all possible values for *button* mouse event
    arguments.
    """
    NONE = ANY = -1
    LEFT = L = _dearpygui.mvMouseButton_Left
    RIGHT = R = _dearpygui.mvMouseButton_Right
    MIDDLE = M = _dearpygui.mvMouseButton_Middle
    X1 = _dearpygui.mvMouseButton_X1
    X2 = _dearpygui.mvMouseButton_X2

mvMouseButton = PointerCode
mvMouseButton.ANY._add_alias_('')
mvMouseButton.ANY._add_value_alias_(None)
mvMouseButton_Left = mvMouseButton.LEFT
mvMouseButton_Right = mvMouseButton.RIGHT
mvMouseButton_Middle = mvMouseButton.MIDDLE
mvMouseButton_X1 = mvMouseButton.X1
mvMouseButton_X2 = mvMouseButton.X2
