from typing import *

from dearpypixl.core import interface
from dearpypixl.core.protocols import *
from dearpypixl.core.appitem import *
from dearpypixl.lib.items import mvWindowAppItem


__all__ = ("Viewport",)




class _FrameCallbackMap(Mapping[int, tuple[ItemCallback, Any]]):
    """An dictionary-like interface for managing a viewport's on-frame
    callbacks. Keys represent a specific frame, while values are 2-tuples
    consisting of the callback that is scheduled to run when rendering that
    frame and the `user_data` it will receive (if any).

    Callbacks are managed by mutating the mapping:
    ```python
    import dearpypixl as dpx

    dpx.Application.create()
    viewport = dpx.Viewport.create()


    # scheduling a callback to run on frame 10
    viewport.frame_callbacks[10] = lambda frame: print(f"called on frame {frame}")

    # scheduling a callback to run on frame 100 with optional `user_data`
    viewport.frame_callbacks[100] = (lambda frame, _, user_data: print(f"called on {user_data} frame {frame}"), "foobar")

    # scheduling a callback to run after rendering the last frame
    viewport.frame_callbacks[-1] = lambda: print("called on exit")

    # delete a scheduled callback — it will not run
    del viewport.frame_callbacks[10]


    viewport.show()
    dpx.start_dearpygui()
    ```

    **NOTE**: Only one instance of this class exists globally. It is created
    when Dear PyPixl is initialized and is accessible via a viewport object's
    :py:property:`Viewport.frame_callbacks` property. Callbacks set using
    Dear PyGui's `set_frame_callback()` and `set_exit_callback()` functions
    are automatically populated in the mapping.
    """
    def __init__(self, /) -> None: ...
    def __len__(self, /) -> int: ...
    def __iter__(self, /) -> Iterator[int]: ...
    def __contains__(self, key: Any, /) -> bool: ...
    def __getitem__(self, frame: int, /) -> tuple[ItemCallback, Any]: ...
    def __setitem__(self, frame: int, value: ItemCallback | tuple[ItemCallback, Any], /) -> None: ...
    def __delitem__(self, frame: int, /) -> None: ...
    @overload
    def get(self, key: int, /) -> tuple[ItemCallback, Any] | None: ...
    @overload
    def get(self, key: int, /, default: tuple[ItemCallback, Any]) -> tuple[ItemCallback, Any]: ...
    @overload
    def get[T](self, key: int, /, default: T) -> tuple[ItemCallback, Any] | T: ...
    @overload
    def set[T: ItemCallback](self, frame: int, /, *, user_data: Any = None) -> Callable[[T], T]: ...
    @overload
    def set[T: ItemCallback | None](self, frame: int, callback: T, /, *, user_data: Any = None) -> T: ...
    @overload
    def pop(self, key: int, /) -> tuple[ItemCallback, Any]: ...
    @overload
    def pop[T](self, key: int, default: T, /) -> tuple[ItemCallback, Any] | T: ...
    @overload
    def pop[T](self, key: Any, default: T, /) -> T: ...
    def popitem(self, /) -> tuple[int, tuple[ItemCallback, Any]]: ...
    def clear(self, /) -> None: ...




type _ViewportCallback = ItemCallback[int | str, tuple[int, int, int, int], Any]
type _FrameBufferCallback = ItemCallback[int | str, mvBuffer, Any]

class _ViewportBaseConfigDict(TypedDict, total=False):
    title        : str
    small_icon   : str
    large_icon   : str
    width        : int
    height       : int
    x_pos        : int
    y_pos        : int
    min_width    : int
    max_width    : int
    min_height   : int
    max_height   : int
    resizable    : bool
    vsync        : bool
    always_on_top: bool
    decorated    : bool
    clear_color  : Array[float, Literal[3, 4]]
    disable_close: bool

class _ViewportConfigDict(_ViewportBaseConfigDict, total=False):
    primary_window: Item | None
    callback      : _ViewportCallback | None
    user_data     : Any

class _ViewportStateDict(TypedDict, total=True):
    ok: bool
    pos: list[int]
    rect_size: list[int]
    fullscreen: bool


class Viewport(interface.Interface):
    @property
    def tag(self, /) -> int | str: ...
    @classmethod
    def create(cls, **configuration: Unpack[_ViewportConfigDict]) -> Self: ...
    def destroy(self) -> None: ...
    @property
    def client_width(self) -> int: ...
    @property
    def client_height(self) -> int: ...
    @property
    def title(self, /) -> str: ...
    @title.setter
    def title(self, value: str, /) -> None: ...
    @property
    def small_icon(self, /) -> str: ...
    @small_icon.setter
    def small_icon(self, value: str, /) -> None: ...
    @property
    def large_icon(self, /) -> str: ...
    @large_icon.setter
    def large_icon(self, value: str, /) -> None: ...
    @property
    def width(self, /) -> int: ...
    @width.setter
    def width(self, value: int, /) -> None: ...
    @property
    def height(self, /) -> int: ...
    @height.setter
    def height(self, value: int, /) -> None: ...
    @property
    def x_pos(self, /) -> int: ...
    @x_pos.setter
    def x_pos(self, value: int, /) -> None: ...
    @property
    def y_pos(self, /) -> int: ...
    @y_pos.setter
    def y_pos(self, value: int, /) -> None: ...
    @property
    def min_width(self, /) -> int: ...
    @min_width.setter
    def min_width(self, value: int, /) -> None: ...
    @property
    def max_width(self, /) -> int: ...
    @max_width.setter
    def max_width(self, value: int, /) -> None: ...
    @property
    def min_height(self, /) -> int: ...
    @min_height.setter
    def min_height(self, value: int, /) -> None: ...
    @property
    def max_height(self, /) -> int: ...
    @max_height.setter
    def max_height(self, value: int, /) -> None: ...
    @property
    def resizable(self, /) -> bool: ...
    @resizable.setter
    def resizable(self, value: bool, /) -> None: ...
    @property
    def vsync(self, /) -> bool: ...
    @vsync.setter
    def vsync(self, value: bool, /) -> None: ...
    @property
    def always_on_top(self, /) -> bool: ...
    @always_on_top.setter
    def always_on_top(self, value: bool, /) -> None: ...
    @property
    def decorated(self, /) -> bool: ...
    @decorated.setter
    def decorated(self, value: bool, /) -> None: ...
    @property
    def clear_color(self, /) -> Array[int | float, Literal[3, 4]]: ...
    @clear_color.setter
    def clear_color(self, value: Array[int | float, Literal[3, 4]], /) -> None: ...
    @property
    def disable_close(self, /) -> bool: ...
    @disable_close.setter
    def disable_close(self, value: bool, /) -> None: ...
    @property
    def primary_window(self, /) -> mvWindowAppItem | None: ...
    @primary_window.setter
    def primary_window(self, value: int | str | None, /): ...
    @primary_window.deleter
    def primary_window(self, /) -> None: ...
    @property
    def callback(self, /) -> _ViewportCallback | None: ...
    @callback.setter
    def callback(self, value: _ViewportCallback | None, /) -> None: ...
    @callback.deleter
    def callback(self, /) -> None: ...
    @property
    def user_data(self, /) -> Any: ...
    @user_data.setter
    def user_data(self, value: Any, /) -> None: ...
    @user_data.deleter
    def user_data(self, /) -> None: ...
    def configure(self, /, **kwargs: Unpack[_ViewportConfigDict]) -> None: ...
    def configuration(self) -> _ViewportConfigDict: ...
    @property
    def pos(self, /) -> list[int]: ...
    @pos.setter
    def pos(self, value: Sequence[int], /) -> None: ...
    @property
    def is_visible(self, /) -> bool: ...
    @overload
    def show(self, *, minimized: bool = ...) -> None: ...
    @overload
    def show(self, *, maximized: bool = ...) -> None: ...
    @property
    def is_fullscreen(self, /) -> bool: ...
    def fullscreen(self, value: bool | None = None, /) -> None: ...
    @property
    def rect_size(self, /) -> list[int]: ...
    def state(self) -> _ViewportStateDict: ...
    def minimize(self, /) -> None: ...
    def maximize(self, /) -> None: ...
    @property
    def frame_callbacks(self, /) -> _FrameCallbackMap: ...
    def get_active_window(self) -> Item | None:
        """Returns the identifier of the foreground root window item."""
    def get_mouse_pos(self, /, *, local: bool = True) -> Array[float, Literal[2]]: ...
    def get_mouse_drag_delta(self, /) -> float:
        """Return the distance the mouse cursor has traveled since
        the last update.
        """
    def get_mouse_plot_pos(self, /) -> Array[float, Literal[2]]:
        """Return the position of the mouse cursor relative to the
        active `mvPlot` item.
        """
    def get_mouse_drawing_pos(self, /) -> Array[float, Literal[2]]:
        """Return the position of the mouse cursor relative to the
        active `mvDrawlist` or  `mvViewportDrawlist` item."""
    def output_frame_buffer(self, file: str = "", *, callback: _FrameBufferCallback | None = None) -> None:
        """Dump the frame buffer as a PNG image. Can only be called if
        at least one frame has been rendered. Unavailable on MacOS.

        Args:
            * file: A filename for the image.

            * callback: A DearPyGui-callable callback. If specified, Dear
            PyGui will call it next frame; passing it a `mvBuffer` object
            as the callback's second positional argument. The buffer will
            contain the raw image data.
        """
